### ISSUE TITLE
Add FGS2 to GUI

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/webbpsf#199]
<a href="https://github.com/laurenmarietta"><img src="https://avatars1.githubusercontent.com/u/12650803?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [laurenmarietta](https://github.com/laurenmarietta)**
_Monday Mar 26, 2018 at 20:01 GMT_
_Originally opened as https://github.com/mperrin/webbpsf/issues/199_

----

Kevin Volk has noticed that there is no option to select FGS2 when simulating FGS PSFs through the GUI.

**Comment by mperrin** [comment]
<a href="https://github.com/mperrin"><img src="https://avatars0.githubusercontent.com/u/1151745?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mperrin](https://github.com/mperrin)**
_Friday Apr 27, 2018 at 22:34 GMT_

----

The GUI is deprecated and not a priority for development. If you or Kevin want to add that, then sure please do submit a PR. But it's not going to be high on our to do list otherwise.

**Comment by mperrin** [comment]
@laurenmarietta In looking back at open WebbPSF issues I was reminded of this one. Since we are trying to encourage people to use the programming interface rather than the GUI for webbpsf, I'm inclined to close this issue without taking any further action. But let me know if you or Kevin find the GUI useful enough that you would want to add this functionality yourself. Otherwise I will close this if it's OK with you.

**Comment by laurenmarietta** [comment]
I don't use the GUI at all, so if Kevin is not passionate about it, feel free to close.

**Comment by mperrin** [comment]
GUI has been deprecated; wontfix.
