### ISSUE TITLE
Add initial support for NIRSpec IFU

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/webbpsf#222]
<a href="https://github.com/mperrin"><img src="https://avatars0.githubusercontent.com/u/1151745?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mperrin](https://github.com/mperrin)**
_Monday Jul 09, 2018 at 16:53 GMT_
_Originally opened as https://github.com/mperrin/webbpsf/issues/222_

----

Details TBD, in coordination with the NIRSpec team.

**Comment by Hoeijmakers** [comment]
Hi Marshall,

I was trying to get WebbPSF to run using the NIRSpec IFU but besides a handle in the filter_list, I discovered that it is not yet implemented. Is this still being worked on? Is the shape of the PSF expected to be qualitatively different in IFU mode compared to the filters that are currently supported?

Thanks!

**Comment by mperrin** [comment]
Hi Jens @Hoeijmakers: The short answer is, there is still not much information available on any particular or expected differences in optical model between the modes. We do know there will be difference but do not have good models for them. You can think of it as, WebbPSF models the PSF as seen _at the IFU slicer entrance plane_ (which is also the MSA plane), but we do not have models for the effect of the slicer, or the precision + accuracy of reconstruction into the data cubes by the pipeline.  Such models have not been provided by the NIRSpec team. 

So, without that, the best we can do is to simulate a monochromatic PSF at some wavelength of interest, and use this as a best-available-estimate proxy for the PSF of the NIRSpec IFU at those wavelengths. This leaves out some details of course...

That said, we have finally (only within the last few months) at last gotten some simulated high-fidelity data cubes from the NIRSpec IPS simulator and processed via the JWST data pipeline. Broadly speaking the PSFs produced by that are pretty well consistent with those from WebbPSF. They are a little broader in FWHM and more smoothed out, which I believe is due to the exponentially weighted interpolation used in the data pipeline. To first order, I found last week this can be roughly approximated by applying a slight smoothing filter to the WebbPSF output using a Gaussian with width ~ 0.6 pixels, for instance `scipy.ndimage.gaussian_filter(psf_data, 0.6)`.  This is only a rough approximation of course, and there are more complex systematics in the pipeline (which is still in active development of course). 

Glad to hear you are interested in this - I am quite excited about the possibilities of NIRSpec IFU for high contrast imaging myself, and I think this is an area that needs a lot more attention than it has gotten thus far. In the near future we are hoping to have available some more simulated datasets for NIRSpec IFU modes, including some generated for the ERS program and some for various GTO programs including one of my own. I encourage you to contact the help desk here at STScI if you are interested in such simulations. Happy to talk more on any particular details of other simulations using WebbPSF that you may be interested in as well.

**Comment by Hoeijmakers** [comment]
Hi Marshall @mperrin 

Thanks for that extensive answer! I actually was playing around with the monochromatic wavelengths in combination with either of the available filters (F110W and F140X), but at G395-wavelengths. The monochromatic PSFs initially surprised me a bit, because they show a lot of fine diffraction patterns that are (of course) not apparent on the wideband PSFs the ETC appears to use.

I'm indeed interested in exploring direct imaging strategies with the NIRSpec IFU, and I am fairly confident that what I wish to do can be achieved; but I wasn't sure to what extent I could rely on the PSF that the ETC uses.

I would absolutely be interested in such simulations, and I will be in touch with STScI.

**Comment by mperrin** [comment]
The choice of filter is irrelevant for monochromatic simulations. The filter model is only used for computing the relative spectral response weighting in broadband imaging modes, which for NIRSpec means only the target acquisition mode. 

Since it’s an all-reflective instrument there is no wavelength dependent component expected or modeled in the wavefront error, unlike NIRCam which is refractive and thus has chromatic wavefront error

**Comment by mperrin** [comment]
Won't do; we do not have any detailed optical model information on NIRSpec IFU WFE at this point. Thus far it has seemed to be the case for the NIRSpec team that it suffices to use imaging mode monochromatic PSFs (i.e. with image_mask='None') when needed for the IFU.
