### ISSUE TITLE
Documentation build failing on Travis

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/webbpsf#233]
The docs build for WebbPSF is failing consistently right now. @robelgeda could you take a look at this please, and see if you can figure out what’s going on? Thanks

**Comment by mperrin** [comment]
@robelgeda, just checking in to see if you think you will have time to look at this problem this week?

**Comment by robelgeda** [comment]
Sorry about the late reply. I took a look at it and I think #238 should fix it.

**Comment by mperrin** [comment]
This was fixed a while ago and the docs build successfully on Travis now.
