### ISSUE TITLE
Set use_2to3 to False in setup.py?

### ISSUE THREAD

**Issue by laurenmarietta** [spacetelescope/webbpsf#234]
@kjbrooks identified a problem when installing `webbpsf` in developer mode (i.e. either by `pip install -e .` or by `python setup.py develop`) where the package was being built and then run from  a `build/` directory, rather than the source code.

The primary effect of this is that the installation isn't really edittable; if a file in `webbpsf/` is changed, that change would not be registered in the package unless the install command was run again and the files in the `build/` directory were updated.

It seems that this behavior is coming from the `use_2to3=True` definition in `setup.py` (line 131). From what I can glean from the [setuptools documentation](https://setuptools.readthedocs.io/en/latest/python3.html) and [StackOverflow](https://stackoverflow.com/questions/35734519/why-after-setup-py-develop-new-submodules-are-not-available/35735171#35735171), it seems as though this option assumes that the source code is written in Python 2, and the code in the `build/` directory is thus the result of `setuptools` converting the code into Python 3.

Since `webbpsf` is written in Python 3 (right?), it seems like it would be beneficial to remove the `use_2to3` option, as it is unnecessary and makes developing more complicated.

**Comment by mperrin** [comment]
Good sleuthing to @kjbrooks and you for figuring this out! You’re correct, as of very recently WebbPSF is now Py3.5+ only, so by all means let’s clean this out. It’s vestigial from so long ago I didn’t even remember this was on.
