### ISSUE TITLE
unresolved references in opd.py?

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/webbpsf#235]
Split to its own issue from #232:

@laurenmarietta wrote:
> Also, a general comment: I am starting to play around with PyCharm's inspections feature, and there seem to be a lot of broken pieces in opds.py (namely, 48 apparently unresolved references). Just making sure someone is aware of this!

And @mperrin [wrote](https://github.com/spacetelescope/webbpsf/pull/232#issuecomment-422044396):

> Surprised to hear about the unresolved references in opds.py. I don't see those when running the Pycharm inspector on it here on my side. In which functions are you seeing those? Let's take a look together sometime.

**Comment by laurenmarietta** [comment]
I'm definitely happy to go through them at length sometime, but to give you an idea, here are some examples of the problems I'm seeing:
- References to attributes of the `OPD` class that don't seem to exist (`data`, `state`, `_move`)
- Calling a module called `SFT` whose import statement has been commented out
- Trying to import a local module `geometry`that doesn't seem to be in the repo anymore
- Trying to create instances of a class called `OPDbender` that isn't defined in the file
And then a number of the other unresolved references are coming from problems within the docstrings (#231).
