### ISSUE TITLE
Missing module "geometry"?

### ISSUE THREAD

**Issue by laurenmarietta** [spacetelescope/webbpsf#243]
I'm working with the `OPD` class within `opds.py`. I have found a tantalizing method called `_rot_matrix_local_to_global()` that seems to intend to transform between local segment control coordinates and a global coordinate system. However, within this method there is a broken import of a module called `geometry`. See the method here:

https://github.com/spacetelescope/webbpsf/blob/master/webbpsf/opds.py#L415 

Is this just pseudocode that was not labeled as such, or was there once a `geometry` module that has been moved elsewhere?

**Comment by laurenmarietta** [comment]
Okay, good to know! I'll leave it up to you to push it or not. I understand not wanting to push something that hasn't been tested.

I've been looking at using some of the attributes within the `OPD` class to do the transformations from scratch instead, from scratch.

**Comment by mperrin** [comment]
Which transformations are you trying to do? The coordinate system geometry is pretty complicated, since each segment has its own unique local coordinate system.

**Comment by laurenmarietta** [comment]
Just a rough translation to keep track of the angles between each segment's X/Y and the detector X/Y. I'm ultimately trying to define the (linear?) relationship between the segment tilt and the displacement of the PSF on the detector. 

It's looking like I can just use the `OPD._control_xaxis_rotations` attribute to work all that out, though.

**Comment by mperrin** [comment]
This file was added at some point in the past. Not sure when but in any case it's not missing now.
