### ISSUE TITLE
OTE pupil amplitude not applied during calc_psf

### ISSUE THREAD

**Issue by laurenmarietta** [spacetelescope/webbpsf#244]
I am not 100% sure if this is a bug or a feature, but it seems suspect.

If you define an OPD in the following way, where `some_ote_object` is an `OTE_Linear_Model_WSS` object:
```python
ote_as_fits = some_ote_object.as_fits()
nc = webbpsf.NIRCam()
nc.pupilopd = ote_as_fits
```
then when `calc_psf` is run, only the OPD map, and not the pupil amplitude, is used for the calculation. (In this case, `ote_as_fits` is a FITS object that has two extensions, `OPD` and `PUPIL`.)

For example, I used the `webbpsf.enable_adjustable_ote()` functionality to generate an OPD where the mirrors are unaligned and only one segment is included in the pupil. I then tried to use that OPD's fits object to define the OPD for a _different_ webbpsf instrument instance using `nc.pupilopd = ote_as_fits`. The resulting PSF had the effects of the unaligned mirrors, but was calculated for all 18 segments.

For the record, I can get the desired PSF by doing this instead:
```python
ote_as_fits = some_ote_object.as_fits()
nc = webbpsf.NIRCam()
nc, ote = webbpsf.enable_adjustable_ote(nc)
ote.opd = ote_as_fits[0].data
ote.amplitude = ote_as_fits[1].data
```
but I wasn't sure that this is how defining `nc.pupilopd` is supposed to work.

**Comment by laurenmarietta** [comment]
Unfortunately, when I tried to define `nc.pupil = some_ote_object` I got an error that I have since been debugging. 

It seems that when you define the pupil as an HDUList, poppy and webbpsf just grab the 0th extension of that - whereas the HDUList object created by `OPD.as_fits()` has the `OPD` as the 0th extension and the `PUPIL` as the 1st.

I could submit PRs for webbpsf and poppy that fix this by searching for the appropriately named extension rather than just assuming the 0th, if you like.

However, since I found a successuful workaround using `enable_adjustable_ote` I listed above, I am not convinced that would be worth the work. Thoughts?

**Comment by mperrin** [comment]
Curious. It seems to work for me:

```
# Create a NIRCam instance, and assign its pupil to be an OTE linear model.
nc = webbpsf.NIRCam()
ote = webbpsf.opds.OTE_Linear_Model_WSS()
ote.move_seg_local('A3', piston=0.5)  # for example

nc.pupil = ote

# calculate a PSF
psf = nc.calc_psf(nlambda=1, display=True)
```

![unknown](https://user-images.githubusercontent.com/1151745/49252327-b8ece180-f3f1-11e8-9fa1-d751bad61d01.png)

You're absolutely right about this part: 
> It seems that when you define the pupil as an HDUList, poppy and webbpsf just grab the 0th extension of that - whereas the HDUList object created by OPD.as_fits() has the OPD as the 0th extension and the PUPIL as the 1st.
But I don't see why you need a FITS HDUlist _at all_ for what you're trying to do. If you have an OTE model object then that's already something you can just assign to the pupil directly without having to turn it into a FITS file then read that FITS file back into an OpticalElement object. 

(Note, the above code example relies on an internal detail of how WebbPSF passes the `pupil` and `pupilopd` attributes to `poppy`; in this case if `nc.pupil` is an `OpticalElement` object, that takes precedence and the `nc.pupilopd` which is just a string at its default value gets ignored. This is non-obvious, to say the least. The typical use case is those are 2 different FITS filenames (both are strings), or else they both get assigned the same `OTE_Linear_Model_WSS` object (both are objects). As a shortcut it suffices to just assign the `pupil` and then it overrides. But this is getting a bit distracted by details. )

**Comment by laurenmarietta** [comment]
Aha! I see now. I'm sorry, I didn't realize in your previous example that you were just straight passing in the `OTE_Linear_Model_WSS` object. You're absolutely right that the FITS part was unnecessary. Obviously I have been making this harder than it needs to be!

Thank you for clarifying (again) - I will implement this in the MIRAGE code.
