### ISSUE TITLE
Double check SI focus information. 

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/webbpsf#252]
SI defocus models. @obi-wan76 will confer with Telfer about focus information, and determine if any updates are needed. 

- NIRCam defocus vs wavelength. In particular for LW F323N filter defocus.  See #179
- Are there any measured & significant focus variations between the instruments, or are they all entirely confocal within the uncertainties?

Split from #204.

**Comment by JarronL** [comment]
> * NIRCam defocus vs wavelength. In particular for LW F323N filter defocus.  See #179

It think we can mark this bullet point as being complete. During my implementation of the coronagraphic tilt offsets this week, I double-checked the NIRCam wavelength-dependent focus as well as the F323N offsets and am satisfied.

I cannot comment on focus variations between instruments, though.
