### ISSUE TITLE
Ensure it's easy to use OPDs of different size

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/webbpsf#253]
As discussed previously w/ Marcio and JStans, large FOV PSFs needs better sampling. Consider setting up a better supported mode for WebbPSF to use 2048 squared OPDs instead of 1024, for better sampling of the segment gaps (and thus better modeling of the diffraction spikes).

@mperrin, @obi-wan76 can collaborate to make it easier to use the 2048 squared OPDs. If the user selects a 2048 sized pupil, the OPDs should all be upsampled to match automatically.

Split from #204

**Comment by mperrin** [comment]
@obi-wan76 remind me, did you do this already in the most recent update? Could this old issue be marked closed, or is it still useful to keep open?

**Comment by marcio-melendez** [comment]
Yes, this was solved the the most recent update.
