### ISSUE TITLE
Update URLs in README.rst for spacetelescope repo

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/webbpsf#254]
Particularly the URLs for the status icons for Travis and Coveralls etc.

**Comment by mperrin** [comment]
@robelgeda or @shanosborne  could either of you take care of this one please? It should be quick and easy, I just don’t have time this morning myself due to meetings the whole time.  This would need to be done for Poppy and webbpsf both. Thanks!

**Comment by shanosborne** [comment]
@mperrin @robelgeda Yep - I can do it!

**Comment by shanosborne** [comment]
It looks like the urls have already been updated in poppy, so I just updated the WebbPSF ones.
