### ISSUE TITLE
Improve data file release engineering

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/webbpsf#266]
Some ideas:

- [x] Update the scripts in dev_utils to work on Central Store and from e.g. telservN, rather than assuming it's being ran on some local Mac (with paths to /tmp that don't work on Linux on telserv)
- [ ] ~~Save the output zip files to /itar/jwst/tel/share/webbpsf ? (Or, maybe don't do this automatically because we don't want to store them there until we are sure things are working as desired?).~~ Update: no longer desired. Eventually we move files onto a public Box folder now, which is done by hand
- [ ] ~~Put the downloads in some team-writable area rather than just in Marshall's home directory.~~ See prior comment. Box used now.  
- [ ] Automate the part where it unzips the new file, set the environment variable for WEBBPSF_PATH appropriately, and runs all the tests. 
 - [ ] Put version number in minimal data zip file too

**Comment by mperrin** [comment]
Partly done in #454

**Comment by mperrin** [comment]
@BradleySappington I noticed this very old issue about data file release engineering. I'm not sure there is much value in keeping open this years-old issue any more? I know you did some work not long ago to improve the data files release process a bit. What do you think, should we close this old issue?

**Comment by BradleySappington** [comment]
Yes @mperrin, this is good to close, I believe I did most(all?) of these things over the past few months.
