### ISSUE TITLE
WebbPSF data on Conda 

### ISSUE THREAD

**Issue by robelgeda** [spacetelescope/webbpsf#272]
**Outdated, see comments below**
Currently there is an old version of the WebbPSF data on conda and it can be accessed as follows:
`conda install webbpsf-data`

this ether needs to be updated or removed (if we no longer use conda for data distribution)
i.e. `webbpsf-data: 0.6.0-1`is currently installed when running the command above.

**Comment by robelgeda** [comment]
The documentation needs to be updated if we no longer use conda to install the supplemental data:
<img width="758" alt="screen shot 2018-12-20 at 7 34 49 pm" src="https://user-images.githubusercontent.com/10345916/50318334-69e51a00-048e-11e9-84d3-ae7700fb546f.png">

**Comment by robelgeda** [comment]
Ah it looks like the default version is `0.6.0` for some reason. I was able to install 0.8 without any problems when I specified the version. It may be useful to state that you need to do this in the documentation.

**Comment by mperrin** [comment]
This isn’t intentional at all. Conda ought to be giving the most recent version of webbpsf-data by default, not giving an older version still. @jhunkeler can you maybe help take a look at this, please?

**Comment by mperrin** [comment]
See https://github.com/astroconda/astroconda-contrib/pull/439 which is the PR from @shanosborne that updated Conda to have webbpsf data 0.8. Not sure why it would still be giving out 0.6 by default. Thanks for reporting the bug @robelgeda

**Comment by robelgeda** [comment]
That fixed it for me, thanks @jhunkeler!
