### ISSUE TITLE
In webbpsf data 0.8.0 on conda, FGS_throughput.fits does not have a WAVEUNIT keyword

### ISSUE THREAD

**Issue by york-stsci** [spacetelescope/webbpsf#276]
In order to test one of the da5 notebooks, I installed webbpsf 0.8.0 via conda. When creating a PSF grid for the FGS with

`fgs = webbpsf.FGS()`
`fgs.filter = "FGS"`
`grid = fgs.psf_grid(fov_pixels=350, oversample=3, add_distortion=True, nlambda=30)`

(the supplied keyword arguments are part of what the notebook is describing here, and probably not relevant to the issue), I get the following warning:

The supplied file, $WEBBPSF_PATH/FGS/filters/FGS_throughput.fits, does not have a WAVEUNIT keyword. Assuming it is Angstroms.

Looking at the file itself, it appears that the wavelength is supplied in angstroms, so it's doing the correct thing, but adding in the WAVEUNIT keyword would still be a good idea. When I edit my local copy of FGS_throughput.fits to have a WAVEUNIT keyword, and set its value to 'Angstroms', the warning is no longer generated.

**Comment by mperrin** [comment]
Thanks. We should address this as part of the #271 issue to refresh the data files this spring.

**Comment by mperrin** [comment]
Fixed in the 0.9.0 data release.
