### ISSUE TITLE
WFI Detector Field Coverage 

### ISSUE THREAD

**Issue by robelgeda** [spacetelescope/webbpsf#296]
Blocking: #294
@shanosborne  and I found that the current reference data does not cover all pixels in a given WFI detector. Each detecter has 5 field points. Four at the corners and one at the center:
![WFI_Points](https://user-images.githubusercontent.com/10345916/56379629-27cea980-61de-11e9-978f-1b54bce0ab3d.png)

We interpolate between these points to determine the field dependance of the PSF at a given point. The reference data does not cover all corners which leads to an inability to interpolate aberration terms for border pixels. The reference data is indented by a 4 pixel margin:
![WFI_Points_corner](https://user-images.githubusercontent.com/10345916/56380460-328a3e00-61e0-11e9-8702-6d8de177cc4e.png)

When the user selects a pixel outside the area covered by the interpolation, an exception is raised:
`RuntimeError("Attempted to get aberrations for an out-of-bounds field point")`

The reasoning behind the placement of the field points can be found in this code comment:
https://github.com/spacetelescope/webbpsf/blob/master/webbpsf/wfirst.py#L197%03-L202

The question is now how to handle this error? Should we inform the user that they picked a valid pixel and that it is out of bound of the ref data? Should we extrapolate or estimate  (closest point approximation)?

**Comment by mperrin** [comment]
This is just semantics in some sense. The outer 4 pixels of all detectors are not photo sensitive, they're the reference pixels used for calibrating out detector systematics. So you actually _cannot get a PSF from those pixels at all_. 

That said the PSF will change essentially not at all over the span of 4 pixels. So I would be completely fine with just saying if the field point is outside of the allowed range, just use the closest pixel that is inside the allowed area.

**Comment by mperrin** [comment]
Incidentally the statement about the outer 4 pixels being not photosensitive is also true about the JWST detectors. But there we don't even have WFE models as close as 4 pixels to the edge, because the ISIM test field points were chosen to be way inside from the corners.

**Comment by robelgeda** [comment]
Ah, that makes sense, thanks! 
I will post a patch PR soon.
