### ISSUE TITLE
Update WFI optical models

### ISSUE THREAD

**Issue by shanosborne** [spacetelescope/webbpsf#301]
We are expecting to get an update from Goddard on the WFI optical models which will need to be implemented in the WFI class.

@robelgeda said he would be handling this and @Skyhawk172 can shadow him, so tagging you both so you see this.

**Comment by mperrin** [comment]
The point of contact at Goddard is Jeff Kruk. We should consider pinging him for a status update if we have not heard anything by next week. Jeff told me on 4/11 that this data was expected by the end of this week.

**Comment by shanosborne** [comment]
@mperrin Checking in on this - have we received this data yet?

**Comment by mperrin** [comment]
Not as far as I know. @robelgeda, have you heard anything yet? If not I can email Jeff.

**Comment by shanosborne** [comment]
I asked @robelgeda and he said that no one has contacted him

**Comment by mperrin** [comment]
Ok I will email Jeff.

**Comment by mperrin** [comment]
This will be addressed by PR #309

**Comment by mperrin** [comment]
Done in #309
