### ISSUE TITLE
Specify out_dir for psf_grid

### ISSUE THREAD

**Issue by laurenmarietta** [spacetelescope/webbpsf#303]
It would be useful if users could provide two separate arguments - `out_dir` and `filename`, say - to `psf_grid()` in order to override the default save location. 

Only allowing the user to provide a full `outfile` path with the path and filename included is less flexible. Additionally, I could foresee problems arising from the difference between the default naming format and the naming format when `outfile` is specified, if a user is searching for names of a given format.

**Comment by shanosborne** [comment]
Reminding myself of another bug here - change `self.filename.split(".")[0]` to `self.filename.split(".fits")[0]`

**Comment by shanosborne** [comment]
@mperrin, was there a reason we didn't originally have separate directory and filename keywords in `psf_grid`? I feel like there was but now I can't remember

**Comment by mperrin** [comment]
Not that I can remember! I like the suggested functionality of being easily able to use the default file naming format but specify some desired output directory.

**Comment by mperrin** [comment]
@shanosborne I can't quite tell if this old open issue is still applicable or not, or if you addressed it at some point in the last two years, perhaps in the commits on PR 294? Let me know if you think this issue should stay open now or not, please

**Comment by shanosborne** [comment]
It looks like an `outdir` parameter was added to `CreatePSFLibrary` in PR 294, so this issue can be closed
