### ISSUE TITLE
Remove use of astropy-helpers submodule

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/webbpsf#307]
See astropy/astropy-APEs#52 ("A roadmap for package infrastructure without astropy-helpers") which describes how the functionality in astropy-helpers can be achieved via more standardized tools in the Python ecosystem. 

This is clearly good and we should do it. 

See for instance https://github.com/spacetelescope/mosviz/pull/179 and https://github.com/spacetelescope/cubeviz/pull/492 for examples of PRs that remove astropy-helpers. We should do similarly here.

**Comment by mperrin** [comment]
@shanosborne, @robelgeda: Do either of you think you might have time to assist with this? Similar changes needed in both poppy and webbpsf, which should lead to overall more maintainable package setups.

**Comment by shanosborne** [comment]
@mperrin yes I can start looking into this

**Comment by shanosborne** [comment]
Just an update that I've started working on this for both webbpsf and poppy. Sorry for the delay, but I'm planning to get it done this week as long as nothing goes terribly wrong

**Comment by mperrin** [comment]
No need to apologize for any delay - I've been out the last two weeks on vacation, I've certainly not been doing anything productive around here myself! :-)

**Comment by pllim** [comment]
APE 17 is accepted. Look out for a "conversion guide" that Tom Robitaille will send out to astropy dev mailing list in the near future.

**Comment by mperrin** [comment]
Hi @shanosborne it would be nice to return to this now and get it taken care of, since the astropy APE to depreciate the helpers module is finalized now. Once you're back in the office, can you follow up with Pei Lian or with Tom Robitaille about the conversion guide mentioned in the comment just above, please?  

There are also some recent PRs showing examples of de-helper-ifying other packages, for instance https://github.com/spacetelescope/wss_tools/pull/65

**Comment by pllim** [comment]
If you have entry points, also see spacetelescope/wss_tools#66

**Comment by mperrin** [comment]
Closed by #337
