### ISSUE TITLE
WFIRST instruments' calc_psf functions don't support distortion

### ISSUE THREAD

**Issue by ariedel** [spacetelescope/webbpsf#315]
The WFIRST instruments crash if you try to pass the distortion parameter to them in calc_psf.

For ease of programming to the API, I'd prefer to have them at least accept a distortion keyword, even if it does nothing or needs to be set to False.

**Comment by mperrin** [comment]
Makes sense to me, sure.

**Comment by robelgeda** [comment]
@mperrin Should this go into the Poppy codebase? If we add the keyword in WebbPSF we would have to override the poppy instrument class. Not sure which approach is the best.

**Comment by mperrin** [comment]
Actually, it belongs here - we _do_ override the base class to add that keyword to `calc_psf` in the `JWInstrument` class.  Adric's request is that we do so consistently in `WFIRSTInstrument` as well.

**Comment by robelgeda** [comment]
Sounds good to me

**Comment by mperrin** [comment]
@robelgeda Here's another quite old WFI issue, which I'm not sure if it's been addressed or not yet. Can you give an update on the status for this, please? @ariedel I realize this issue is now two years old but I think the same principle applies still that we would want a consistent API for both the JWST and Roman instruments.

**Comment by robelgeda** [comment]
I am not sure if this is fixed actually. I think we need to make a `calc_psf` function for the roman instrument? If so, this needs to stay open.

**Comment by ariedel** [comment]
I believe it is not fixed - webbpsf_core shows a custom calc_psf function that reads the distortion and then passes the rest of the parameters to JWInstrument; Roman has no such thing and directly runs the poppy calc_psf function.

**Comment by mperrin** [comment]
@ojustino - here is another Roman-related webbpsf issue. I think this is a relatively straightforward small fix to ensure a consistent API between the Roman and JWST classes, but Robel never got around to it. Now that you're picking up the Roman side of things this would be good to add into the plan (though not as high a priority as the Cycle 9 stuff, of course).
