### ISSUE TITLE
Missing pysynphot link in docs

### ISSUE THREAD

**Issue by shanosborne** [spacetelescope/webbpsf#329]
Message from JWST Help Desk:

> Hi, Folks:
> 
> I write to alert you to a possible typo in the documentation for installing
> WebbPSF. This passage
> <https://webbpsf.readthedocs.io/en/stable/installation.html#pysynphot-install>
> of the WebbPDF requirements document contains the following statement:
> 
> Further installation instructions can be found in the pysynphot docs or a
> discussion in the POPPY docs
> <http://poppy-optics.readthedocs.io/en/stable/installation.html#installing-or-updating-pysynphot>
> .
> 
> It looks to me as if "the synphot docs" was intended to be a link to
> another web page (perhaps this
> <https://webbpsf.readthedocs.io/en/stable/installation.html#pysynphot-install>)
> rather than simply being typeset in a different font. If that's the case,
> could you please consider updating the document to include that link?
> 
> Cheers,
> 
> Greg
> 
> -- 
> Gregory D. Wirth
> Phone: 808.217.2605
> LinkedIn: http://www.linkedin.com/in/gregorydwirth/

**Comment by mperrin** [comment]
Hi @shanosborne  - are you going to be able to investigate this one? I expect is it some simple formatting issue with the RST syntax that's causing the link to not show up. Probably a very easy / quick fix...

**Comment by shanosborne** [comment]
Yes I can fix this, I just haven't had time yet with WFR prep. I'll try to get to it today/tomorrow!

**Comment by mperrin** [comment]
Fixed in #330.
