### ISSUE TITLE
Problem with NIRSpec Zernike interpolation

### ISSUE THREAD

**Issue by ariedel** [spacetelescope/webbpsf#331]
When I make PSFs with WebbPSF 0.9.0, there are large differences between the NIRSpec PSF grid, when compared to the other instruments.

From what I can tell, the difference appears to be that the NIRSpec PSFs come out with SIWFETYP="Extrapolated".

What I know: the DET_V2 and DET_V3 values have not changed. 
The field point ISIM1 in si_zernikes_isim_cv3.fits has (what appears to be) the same data in both WebbPSF 0.8.0 and WebbPSF 0.9.0. 
In the new files, all of the results of cubic interpolation of the Zernikes are nan. 
The SI WFE coeff for the Zernike terms appears to just be the Zernike terms from the si_zernikes_isim_cv3.fits file.

The point being queried does seem to be outside of the cluster of defined field points (see chart) but either this has always been true and it somehow worked, or a field point has been moved.
![Fieldpoints](https://user-images.githubusercontent.com/2412871/70480566-0e9ca500-1aae-11ea-9872-8083936972be.png)

**Comment by mperrin** [comment]
@JarronL would you be able to help take a look at this, please?

**Comment by mperrin** [comment]
@ariedel Jarron and I are talking now. We're questioning where the input coordinates you're using have come from. The point marked in orange is outside the NIRSpec field of view: 

<img width="780" alt="Screen Shot 2019-12-12 at 4 13 06 PM" src="https://user-images.githubusercontent.com/1151745/70749424-5152bd00-1cfa-11ea-82a7-0c9bb9489fbd.png">

So, that's not a great choice of position for a reference PSF location. 

The prior version of WebbPSF, given this coordinate, simply failed back to using the closest available field point (with no interpolation or extrapolation). The new version tried to extrapolate. In this case I think that asking an extrapolation all the way outside the field of view of the instrument is probably not reasonable or useful. So I think the right fix is going to be to adjust the input position so it's actually at the ISIM1 field point instead. That should give a PSF consistent with what was output before.

**Comment by mperrin** [comment]
There's a separate issue why it's NaNs. @JarronL says he will look into that (not this week, due to SI rehearsal).



For the position issue highlighted above, I think I know what's going on. WebbPSF's default behavior is to start with the center coordinates of the detector in question, e.g. (1024, 1024) for any of the H2RGs. For most instruments this is a reasonable default. For NIRSpec not so much, because it's outside of the field of view in imaging mode. (The mapping between detector pixel and V2V3 coordinates is much more complicated for a spectrograph than an imager, of course. Once you disperse photons, you can get light to that detector pixel, even though it's outside the FOV in imaging mode).  

Previously this behavior was no problem because the WFE outside the FOV just failed back to the closest field point, in this case ISIM1. 

The easiest fix here is to update your code to set the detector position to `(1380, 1024)` instead of the default `(1024, 1024)`. That will should the selected point for the PSF computation to be almost exactly on top of the ISIM1 field point, and therefore should yield PSFs consistent with those you had before. (And as a bonus, it also makes way more physical sense!)

**Comment by JarronL** [comment]
@ariedel I'm unable to replicate your issue with the latest version of `webbpsf` (0.9.1) as it resides on GitHub. I'm using `poppy` v0.8.0. 

Here's my example code, which defaults to pixel position `detx, dety = (1024,1024)` or `v2, v3 = (4.9, -8.4)`, which utilizes the extrapolation code:
``` python
import webbpsf
inst = webbpsf.NIRSpec()
hdul_psf = inst.calc_psf(monochromatic=2e-6)
```

Resulting `hdul_psf[0].header`:
```
SIMPLE  =                    T / conforms to FITS standard                      
BITPIX  =                  -64 / array data type                                
NAXIS   =                    2 / number of array dimensions                     
NAXIS1  =                  192                                                  
NAXIS2  =                  192                                                  
EXTEND  =                    T                                                  
PLANE1  = 'Wavefront Intensity'                                                 
WAVELEN =                2E-06 / Weighted mean wavelength in meters             
DIFFLMT =  0.06247169856520649 / Diffraction limit lambda/D in arcsec           
OVERSAMP=                    4 / Oversampling factor for FFTs in computation    
DET_SAMP=                    4 / Oversampling factor for MFT to detector plane  
PIXELSCL=             0.026075 / Scale in arcsec/pix (after oversampling)       
FOV     =               5.0064 / Field of view in arcsec (full array)           
NWAVES  =                    1 / Number of wavelengths used in calculation      
WAVE0   =                2E-06 / Wavelength 0                                   
WGHT0   =                    1 / Wavelength weight 0                            
FFTTYPE = 'numpy.fft'          / Algorithm for FFTs: numpy or fftw              
NORMALIZ= 'first   '           / PSF normalization method                       
JITRTYPE= 'Gaussian convolution' / Type of jitter applied                       
JITRSIGM=                0.007 / Gaussian sigma for jitter [arcsec]             
JITRSTRL=    0.998881771137093 / Strehl reduction from jitter                   
PUPILINT= 'jwst_pupil_RevW_npix1024.fits.gz' / Pupil aperture intensity source  
PUPILOPD= 'OPD_RevW_ote_for_NIRSpec_requirements.fits.gz' / Pupil OPD source    
INSTRUME= 'NIRSpec '           / Instrument                                     
FILTER  = 'F110W   '           / Filter name                                    
EXTNAME = 'OVERSAMP'           / This extension is oversampled.                 
DATE    = '2020-01-06T19:08:00' / Date of calculation                           
AUTHOR  = 'jwstnircam@aegonii' / username@host for calculation                  
CORONMSK= 'MSA all open'       / Image plane mask                               
PUPIL   = 'NIRSpec grating'    / Pupil plane mask                               
VERSION = '0.9.1   '           / WebbPSF software version                       
DATAVERS= '0.9.0   '           / WebbPSF reference data files version           
DET_NAME= 'NRS1    '           / Name of detector on this instrument            
DET_X   =               1024.5 / Detector X pixel position of array center      
DET_Y   =               1024.5 / Detector Y pixel position of array center      
DET_V2  =     4.89969871652295 / [arcmin] Det. pos. in telescope V2,V3 coord sys
DET_V3  =   -8.381608680644254 / [arcmin] Det. pos. in telescope V2,V3 coord sys
TEL_WFE =    186.9360414967025 / [nm] Telescope pupil RMS wavefront error       
SI_WFE  =     26.4221664696923 / [nm] instrument pupil RMS wavefront error      
SIWFETYP= 'Extrapolated'       / SI WFE was extrapolated outside available meas.
SIWFEFPT= 'ISIM1   '           / Closest ISIM CV3 WFE meas. field point         
SIZERN1 = 1.13691671094148E-08 / [nm] SI WFE coeff for Zernike term 1           
SIZERN2 = -6.7707892800841E-09 / [nm] SI WFE coeff for Zernike term 2           
SIZERN3 = 5.22364393611326E-09 / [nm] SI WFE coeff for Zernike term 3           
SIZERN4 = 4.57061406541484E-08 / [nm] SI WFE coeff for Zernike term 4           
SIZERN5 = -2.0585179123847E-08 / [nm] SI WFE coeff for Zernike term 5           
SIZERN6 = -3.0728312505711E-08 / [nm] SI WFE coeff for Zernike term 6           
SIZERN7 = 1.27292536617298E-08 / [nm] SI WFE coeff for Zernike term 7           
SIZERN8 = -1.9744595251234E-08 / [nm] SI WFE coeff for Zernike term 8           
SIZERN9 = 2.42602001662693E-08 / [nm] SI WFE coeff for Zernike term 9           
SIZERN10= 1.15634481406594E-08 / [nm] SI WFE coeff for Zernike term 10          
SIZERN11= 2.52259911071616E-08 / [nm] SI WFE coeff for Zernike term 11          
SIZERN12= 9.37638810974438E-09 / [nm] SI WFE coeff for Zernike term 12          
SIZERN13= 4.93092702058471E-09 / [nm] SI WFE coeff for Zernike term 13          
SIZERN14= -9.4169674202977E-09 / [nm] SI WFE coeff for Zernike term 14          
SIZERN15= -7.5268458601105E-10 / [nm] SI WFE coeff for Zernike term 15          
SIZERN16= -3.4369813808907E-09 / [nm] SI WFE coeff for Zernike term 16          
SIZERN17= 9.80803696764714E-09 / [nm] SI WFE coeff for Zernike term 17          
SIZERN18= -7.5027043300646E-09 / [nm] SI WFE coeff for Zernike term 18          
SIZERN19= -1.4728301172453E-08 / [nm] SI WFE coeff for Zernike term 19          
SIZERN20= -1.0248929411046E-11 / [nm] SI WFE coeff for Zernike term 20          
SIZERN21= -3.1173706755899E-09 / [nm] SI WFE coeff for Zernike term 21          
SIZERN22= 5.50736575887285E-09 / [nm] SI WFE coeff for Zernike term 22          
SIZERN23= 1.42084910649266E-10 / [nm] SI WFE coeff for Zernike term 23          
SIZERN24= -3.7024991779853E-09 / [nm] SI WFE coeff for Zernike term 24          
SIZERN25= -5.0178029719950E-10 / [nm] SI WFE coeff for Zernike term 25          
SIZERN26= 2.94687625998223E-09 / [nm] SI WFE coeff for Zernike term 26          
SIZERN27= 3.97976723626955E-09 / [nm] SI WFE coeff for Zernike term 27          
SIZERN28= 3.61537896002008E-09 / [nm] SI WFE coeff for Zernike term 28          
SIZERN29= -5.3133644902256E-09 / [nm] SI WFE coeff for Zernike term 29          
SIZERN30= -1.7364582818505E-10 / [nm] SI WFE coeff for Zernike term 30          
SIZERN31= 1.73156734972957E-09 / [nm] SI WFE coeff for Zernike term 31          
SIZERN32= 4.32873646542110E-10 / [nm] SI WFE coeff for Zernike term 32          
SIZERN33= -1.8443530039097E-09 / [nm] SI WFE coeff for Zernike term 33          
SIZERN34= 3.62871464162957E-11 / [nm] SI WFE coeff for Zernike term 34          
SIZERN35= -9.0092416885619E-10 / [nm] SI WFE coeff for Zernike term 35          
APERNAME= 'NRS1_FULL'          / SIAF aperture name                             
GRATING = 'None    '           / NIRSpec grating element name                   
APERTURE= 'MSA all open'       / NIRSpec slit aperture name                     
HISTORY Created wavefront: wavelength=2e-06 m, diam=6.603464 m                  
HISTORY  using array size (1024, 1024)                                          
HISTORY   Multiplied WF by phasor for Pupil plane: JWST Entrance Pupil          
HISTORY   Propagating wavefront to Coordinate Inversion in y axis.              
HISTORY Inverted axis direction for Y axes                                      
HISTORY   Propagating wavefront to Rotation by 138.400000 degrees counter clockw
HISTORY ise.                                                                    
HISTORY Rotated by 138.40 degrees, CCW                                          
HISTORY   Multiplied WF by phasor for Pupil plane: NIRSpec fore-optics WFE, near
HISTORY  ISIM1                                                                  
HISTORY   Propagating wavefront to Image plane: MSA all open (Analytic).        
HISTORY     Padded WF array for oversampling by 4x                              
HISTORY    FFT (4096, 4096),  to IMAGE plane  scale=0.015617924641301623 arcsec 
HISTORY / pix                                                                   
HISTORY   Multiplied WF by phasor for Image plane: MSA all open (Analytic)      
HISTORY   Propagating wavefront to Pupil plane: Pupil stop at grating wheel (Ana
HISTORY lytic).                                                                 
HISTORY    FFT (4096, 4096),  to PUPIL scale=0.0064486953125 m / pix            
HISTORY   Multiplied WF by phasor for Pupil plane: Pupil stop at grating wheel (
HISTORY Analytic)                                                               
HISTORY   Multiplied WF by phasor for Pupil plane: NIRSpec spectrograph WFE, nea
HISTORY r ISIM1                                                                 
HISTORY   Propagating wavefront to Detector plane: NIRSpec detector (48x48 pixel
HISTORY s, 0.1043 arcsec / pix).                                                
HISTORY     Propagating w/ MFT: 0.0261 arcsec / pix     fov=80.139 lam/D    npix
HISTORY =192                                                                    
HISTORY Calculation completed in 6.696 seconds                                  
HISTORY Created by POPPY version 0.8.0
```

**Comment by ariedel** [comment]
You DO seem to be having the issue I had - I see `SIWFETYP= 'Extrapolated'       / SI WFE was extrapolated outside available meas.` in your printout, which shows it's now picking a point outside the grid. 

For me, that meant large changes relative to the older NIRSpec PSFs, compared to the other three instruments.

**Comment by JarronL** [comment]
Yes, extrapolation is the intended behavior from PR #283. All, I meant is that I am not seeing any NaNs in the reported Zernike coefficients. In previous versions of WebbPSF, any point that was outside the cubic interpolation region would just choose the nearest neighbor in the si_zernikes_isim_cv3.fits. This meant that large swaths of positions in V2/V3 space would calculate the exact same PSF, which is not realistic. So, I implemented an extrapolation code outlined in #283 to get a best estimate of Zernike values outside of the regions sampled during ISIM CV testing. So, as far as I can tell, this is working as intended, unless I'm misunderstanding your point?

**Comment by mperrin** [comment]
@ariedel  - As per the above comments by @JarronL, we think this is working as intended. Do you concur? Please let us know if you think this still needs attention, or if we can mark this issue as closed. Happy to discuss more in person if needed - but I think this is probably good to go as-is, possibly with the adjustment in NIRSpec detector coords that I suggest above for your PSF gen script if you want to maintain more precise repeatability. Let us know, thanks.

**Comment by ariedel** [comment]
I will need to get NIRSpec's decision on this, from @glennjwst or @cherylpavlovsky .

To summarize my understanding:
The defined NIRSpec focus point is outside the region sampled during testing. Previous versions of WebbPSF just picked the closest field point (ISIM1) for their coefficients, but the new one extrapolates to the location of the focus point.

The two options are:
* Continue with the current WebbPSF focus point, where the SI wavefront coefficients are extrapolated outside the defined regions
* Reproduce the old WebbPSF focus point, and manually move the focus to the ISIM1 field point.

**Comment by glennjwst** [comment]
@ariedel , @cherylpavlovsky 
Thank you for requesting our input. But since we have little insight into how this works, I am not sure that I can give an informed decision at this time. I assume that this fix will not go into effect until after the current JWST call for proposals, and therefore is not a risk to confuse the user prior to the May 1 proposal deadline.

I am always concerned about extrapolation, and in this case it seems to have contributed to the problems we currently have. So, moving the focus point back to ISIM1 makes sense if it reproduces the old Webb PSF results.

However, is there a significant difference between 'current WebbPSF results' and 'old WebbPSF results?' Are they the same or different, and if different, which is considered to be the more correct version? Regardless of the focus point chosen, the result considered the most proper is the driving factor. I might also assume that this can be chosen at some time in the future, prior to the cycle 2 call for proposals.

So, what does this tell us about choosing a focus point. I would be happy to discuss this further.

**Comment by ariedel** [comment]
@glennjwst @cherylpavlovsky 
This will absolutely not go into effect until after the current JWST call for proposals.

Neither of the two options are likely to actually be the same as the old WebbPSF 0.8.0 results, because of improvements in WebbPSF itself in version 0.9.0. 
Option 1 would be to use the new extrapolated wavefront coefficients at the actual focus point
Option 2 would move the focus point back to where it effectively was in WebbPSF 0.8 and earlier, and would use at least similar wavefront coefficients to those previous runs. At the very least they would be based on actual measurements.

I can provide you with two sets of PSFs to compare, to see what (if any) the difference between the two options are. I don't know which one is correct, and I think that would depend on the design of the instrument and the accuracy of the extrapolation used. I suspect the extrapolated version is better, given that it tries to compute values where the focus point actually is, but I don't have much basis for that.

**Comment by glennjwst** [comment]
@ariedel @cherylpavlovsky 
I would like to see the two sets, even if it is just for us to get an overall feel for things and note any big discrepancies. I would prefer to have things based on actual measurements, which would point to Option2. But if there are good arguments for consistency among instruments or whatever else that says we should use Option 1, then I would be open to them.

**Comment by ariedel** [comment]
Let's move this discussion to Jira. I've filed JETC-1011 for this.

**Comment by mperrin** [comment]
Discussion moved to JIRA and resolved there, or at least we agreed on the right path forward.  

As there is no actual problem with the code in WebbPSF for Zernike interpolation, I'm going to mark this closed here.
