### ISSUE TITLE
Aberrations at Wavelength Error 

### ISSUE THREAD

**Issue by robelgeda** [spacetelescope/webbpsf#333]
The following error shows up when using `webbpsf.WFI`

`Attempted to get aberrations at wavelength 2e-06 outside the range of the reference data; clipping to closest wavelength 2e-06`
 
This only happens for filters F129 and F158 and they don’t have any throughput at 2e-6.

**Comment by mperrin** [comment]
@robelgeda - just wanted to follow up about this one? Have you had a chance to look at it yet? Thanks. - M

**Comment by mperrin** [comment]
Hi @robelgeda - wanted to follow up again about this issue you self-reported. Is this still an open concern?

**Comment by mperrin** [comment]
Hi @robelgeda, here's an old issue you reported last year. Is this still a concern or has it been fixed subsequently in one of your other updates? Unless I hear otherwise from you, I'm going to assume that this issue can be closed now.

**Comment by robelgeda** [comment]
This has been resolved for those filters, this particular issue can be closed.
