### ISSUE TITLE
Problems running wim_psf_basic_f0v_even.py 

### ISSUE THREAD

**Issue by rmjarvis** [spacetelescope/webbpsf#334]
I've been looking at the new code for rendering WFIRST PSF images [here](https://wfirst.gsfc.nasa.gov/science/WFIRST_Reference_Information.html).  I started with `conda install webbpsf` which seemed to work.  But then running one of your scripts (wim_psf_basic_f0v_even.py), I got an ImportError from poppy:
```
$ python wim_psf_basic_f0v_even.py 
Script to generate WFIRST imaging PSFs for each SCA in the FPA
Please ensure that updates to the zernike file are copied to 
{$HOME}/Projects/WebbPSF/webbpsf-data/WFI/wim_zernikes_cycle8.csv
Traceback (most recent call last):
  File "wim_psf_basic_f0v_even.py", line 139, in <module>
    s_src = webbpsf.specFromSpectralType(sp_type, catalog='phoenix')
  File "/anaconda3/envs/py3/lib/python3.6/site-packages/poppy/utils.py", line 1433, in specFromSpectralType
    import pysynphot
ModuleNotFoundError: No module named 'pysynphot'
```
So it looks like pysynphot isn't properly being registered as a dependency somewhere.  I'd assume poppy, but if not then webbpsf should probably depend on it, since you're using the pysynphot features within poppy. 

I then installed pysynphot, which fixed this problem.  But then I'm getting another error, which I'm not sure what to do with
```
$ python wim_psf_basic_f0v_even.py 
Script to generate WFIRST imaging PSFs for each SCA in the FPA
Please ensure that updates to the zernike file are copied to 
{$HOME}/Projects/WebbPSF/webbpsf-data/WFI/wim_zernikes_cycle8.csv
/anaconda3/envs/py3/lib/python3.6/site-packages/pysynphot/locations.py:46: UserWarning: PYSYN_CDBS is undefined; functionality will be SEVERELY crippled.
  warnings.warn("PYSYN_CDBS is undefined; functionality will be SEVERELY "
/anaconda3/envs/py3/lib/python3.6/site-packages/pysynphot/locations.py:329: UserWarning: Extinction files not found in extinction
  warnings.warn('Extinction files not found in %s' % (extdir, ))
WARNING: AstropyDeprecationWarning: astropy.extern.six will be removed in 4.0, use the six module directly if it is still needed [astropy.extern.six]
Could not find a match in catalog {0} for key {1}. Check that is a valid name in the lookup table, and/or that pysynphot is installed properly.
Traceback (most recent call last):
  File "/anaconda3/envs/py3/lib/python3.6/site-packages/poppy/utils.py", line 1600, in specFromSpectralType
    return pysynphot.Icat(catname, keys[0], keys[1], keys[2])
  File "/anaconda3/envs/py3/lib/python3.6/site-packages/pysynphot/catalog.py", line 104, in __init__
    table = pyfits.open(filename)
  File "/anaconda3/envs/py3/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 151, in fitsopen
    lazy_load_hdus, **kwargs)
  File "/anaconda3/envs/py3/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 390, in fromfile
    lazy_load_hdus=lazy_load_hdus, **kwargs)
  File "/anaconda3/envs/py3/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 1039, in _readfrom
    fileobj = _File(fileobj, mode=mode, memmap=memmap, cache=cache)
  File "/anaconda3/envs/py3/lib/python3.6/site-packages/astropy/utils/decorators.py", line 521, in wrapper
    return function(*args, **kwargs)
  File "/anaconda3/envs/py3/lib/python3.6/site-packages/astropy/io/fits/file.py", line 178, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/anaconda3/envs/py3/lib/python3.6/site-packages/astropy/io/fits/file.py", line 555, in _open_filename
    self._file = fileobj_open(self.name, IO_FITS_MODES[mode])
  File "/anaconda3/envs/py3/lib/python3.6/site-packages/astropy/io/fits/util.py", line 397, in fileobj_open
    return open(filename, mode, buffering=0)
FileNotFoundError: [Errno 2] No such file or directory: 'grid/phoenix/catalog.fits'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "wim_psf_basic_f0v_even.py", line 139, in <module>
    s_src = webbpsf.specFromSpectralType(sp_type, catalog='phoenix')
  File "/anaconda3/envs/py3/lib/python3.6/site-packages/poppy/utils.py", line 1605, in specFromSpectralType
    raise LookupError(errmsg)
LookupError: Could not find a match in catalog {0} for key {1}. Check that is a valid name in the lookup table, and/or that pysynphot is installed properly.
```
Any advice on this would be much appreciated.  Thanks!

**Comment by mperrin** [comment]
Hi @rmjarvis - apologies for not responding back sooner on this (the combination of travel and an overflowing inbox meant I accidentally did not see this issue until today, and meanwhile @robelgeda  has also been out all month so far too). 

Those error messages look like pysynphot not being able to find the data files it wants, in particular the Phoenix stellar spectra template library. Installing pysynphot doesn't automatically install those, in part because there are many different sets of data files and not everyone needs all of them. See https://pysynphot.readthedocs.io/en/latest/ and scroll part way down the page to the "Installation and Setup" section that describes the data files. In particular you'll want the Phoenix stellar models from http://ssb.stsci.edu/cdbs/tarfiles/synphot5.tar.gz

(Yes, this manual installation is not the most convenient - we have automated the data installation for the webbpsf data files, but the pysynphot developers have not yet done the same for their data files. )

Try this out and please let us know how it goes. We'll be glad to assist if you run into any more glitches, but hopefully the above will get it working.

**Comment by mperrin** [comment]
Hi @rmjarvis - I wanted to follow up on this issue from back in January. Were you able to get this working for you? If not, let's talk so we can lend a hand. In particular @robelgeda  could assist with this. If it's working then great, and please let us know so we can mark this issue as resolved. If it's not working then we'll do what we can to get it working. Cheers.

**Comment by rmjarvis** [comment]
Very sorry for the long delay getting back to this.  I'm now working on this again.

I've now downloaded the pysynphot files, and that let things get farther at least, but I'm still getting an error.  The new error is now:
```
$ python wim_psf_basic_f0v_even.py 
Script to generate WFIRST imaging PSFs for each SCA in the FPA
Please ensure that updates to the zernike file are copied to 
{$HOME}/Projects/WebbPSF/webbpsf-data/WFI/wim_zernikes_cycle8.csv
**WARNING**: LOCAL JWST PRD VERSION PRDOPSSOC-027 IS BEHIND THE CURRENT ONLINE VERSION PRDOPSSOC-029
Please consider updating pysiaf, e.g. pip install --upgrade pysiaf or conda update pysiaf
Traceback (most recent call last):
  File "/anaconda3/envs/py3.6/lib/python3.6/site-packages/numpy/core/function_base.py", line 117, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "wim_psf_basic_f0v_even.py", line 187, in <module>
    webbpsf.display_psf(psf,colorbar_orientation='horizontal')
  File "/anaconda3/envs/py3.6/lib/python3.6/site-packages/poppy/utils.py", line 258, in display_psf
    ticks = np.logspace(np.log10(vmin), np.log10(vmax), np.log10(vmax / vmin) + 1)
  File "<__array_function__ internals>", line 6, in logspace
  File "/anaconda3/envs/py3.6/lib/python3.6/site-packages/numpy/core/function_base.py", line 272, in logspace
    y = linspace(start, stop, num=num, endpoint=endpoint, axis=axis)
  File "<__array_function__ internals>", line 6, in linspace
  File "/anaconda3/envs/py3.6/lib/python3.6/site-packages/numpy/core/function_base.py", line 121, in linspace
    .format(type(num)))
TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.
```
I note that the warning about upgrading pysiaf seems to be spurious.  Or at least conda thinks everything is up to date:
```
$ conda update pysiaf
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.
```
I'm not as sure about the warning re location of the zernike files.  I thought the conda installation handled that for me already:
```
$ locate wim_zernikes_cycle8.csv
/anaconda3/envs/py3.6/share/webbpsf-data/WFI/wim_zernikes_cycle8.csv
/anaconda3/pkgs/webbpsf-data-0.9.0-1/share/webbpsf-data/WFI/wim_zernikes_cycle8.csv
```
Thanks for any help you can offer about this.

**Comment by mperrin** [comment]
Hi @rmjarvis  - my colleagues @robelgeda and @Skyhawk172 should be able to help you with this.

**Comment by mperrin** [comment]
This is an old issue from last year that wasn't closed. @robelgeda @Skyhawk172 can either of you comment on whether you were able to help @rmjarvis with this last summer? Should this issue remain open or can it be marked closed, please? Thanks.

**Comment by rmjarvis** [comment]
I pretty much gave up on this.  Also on this issue: https://github.com/spacetelescope/roman_tools/issues/38

If anyone wants to help on either of these, I could get back to it.  But if you want to mark them both WillNotFix or at least WillNotFixUntilCovidIsOver that's fine.

**Comment by robelgeda** [comment]
I am sorry this slipped by for so long. I will take a look at this and keep you posted.

**Comment by mperrin** [comment]
@ojustino - here is another Roman related issue, a bug report, but which Robel never got around to. Now that you're picking up the Roman side of things this would be good to add into the plan (though not as high a priority as the Cycle 9 stuff, of course).

**Comment by ojustino** [comment]
Hi @rmjarvis, I tried taking a look at this issue but couldn't find `wim_psf_basic_f0v_even.py` to run it myself. Is it supposed to be at the NASA page you linked in the original post? I didn't see it in an archived version of that page or the [current iteration](https://roman.gsfc.nasa.gov/science/Roman_Reference_Information.html).

**Comment by rmjarvis** [comment]
It looks like they now live here: https://roman.gsfc.nasa.gov/science/WFI_technical.html
In the zip file called wim_psf_f0v_fullset.zip
Here is a direct link: https://roman.gsfc.nasa.gov/science/2020-01/wim_psf_f0v_fullset.zip

Since it's been a while, I figured I should at least confirm that the problem still exists with current versions of things, so I updated everything to the latest versions in conda.  And I'm happy to report that the script runs apparently successfully with the current version of the webbpsf code. Here is the output now:
```
$ python wim_psf_basic_f0v_even.py 
Script to generate WFIRST imaging PSFs for each SCA in the FPA
Please ensure that updates to the zernike file are copied to 
{$HOME}/Projects/WebbPSF/webbpsf-data/WFI/wim_zernikes_cycle8.csv
**WARNING**: LOCAL JWST PRD VERSION PRDOPSSOC-034 DOESN'T MATCH THE CURRENT ONLINE VERSION PRDOPSSOC-039
Please consider updating pysiaf, e.g. pip install --upgrade pysiaf or conda update pysiaf
WARNING: VerifyWarning: Card is too long, comment will be truncated. [astropy.io.fits.card]
WARNING: VerifyWarning: Card is too long, comment will be truncated. [astropy.io.fits.card]
finished writing PSF file: WFI_PSF_F062_SCA01_x2048_y2048_j008mas_F0V_e
Finished computations for filter F062 
WARNING: VerifyWarning: Card is too long, comment will be truncated. [astropy.io.fits.card]
finished writing PSF file: WFI_PSF_F087_SCA01_x2048_y2048_j008mas_F0V_e
Finished computations for filter F087 
WARNING: VerifyWarning: Card is too long, comment will be truncated. [astropy.io.fits.card]
finished writing PSF file: WFI_PSF_F106_SCA01_x2048_y2048_j008mas_F0V_e
Finished computations for filter F106 
WARNING: VerifyWarning: Card is too long, comment will be truncated. [astropy.io.fits.card]
finished writing PSF file: WFI_PSF_F129_SCA01_x2048_y2048_j008mas_F0V_e
Finished computations for filter F129 
Attempted to get aberrations at wavelength 2e-06 outside the range of the reference data; clipping to closest wavelength 2e-06
WARNING: VerifyWarning: Card is too long, comment will be truncated. [astropy.io.fits.card]
finished writing PSF file: WFI_PSF_F146_SCA01_x2048_y2048_j008mas_F0V_e
Finished computations for filter F146 
WARNING: VerifyWarning: Card is too long, comment will be truncated. [astropy.io.fits.card]
finished writing PSF file: WFI_PSF_F158_SCA01_x2048_y2048_j008mas_F0V_e
Finished computations for filter F158 
Attempted to get aberrations at wavelength 2e-06 outside the range of the reference data; clipping to closest wavelength 2e-06
WARNING: VerifyWarning: Card is too long, comment will be truncated. [astropy.io.fits.card]
finished writing PSF file: WFI_PSF_F184_SCA01_x2048_y2048_j008mas_F0V_e
Finished computations for filter F184 
Finished computations for SCA  1, x_pixel 2048, y_pixel 2048
WARNING: VerifyWarning: Card is too long, comment will be truncated. [astropy.io.fits.card]
finished writing PSF file: WFI_PSF_F062_SCA02_x2048_y2048_j008mas_F0V_e
Finished computations for filter F062 

[... snip ...]

finished writing PSF file: WFI_PSF_F184_SCA12_x4040_y0050_j008mas_F0V_e
Finished computations for filter F184 
Finished computations for SCA 12, x_pixel 4040, y_pixel   50
Finished computations for jitter = 008 mas
Done with all computations!
```
The warning about the wavelength at 2e-06 being outside the range seems like a rounding problem, so someone might want to look into correcting that.  And the astropy Card warnings may be related to [this](https://github.com/spacetelescope/stwcs/issues/36), but that issue claims to have been fixed, so maybe this is a separate but similar problem.

In any case, neither of these are related to the problem I was having, which appears to have been already fixed by some other update.  The script now runs successfully and creates the images it is supposed to.  So I'll close this issue now.  Cheers.
