### ISSUE TITLE
Simulated OTE Mirror Move Demo.ipynb looking for webpsf-data file that doesn't exist

### ISSUE THREAD

**Issue by kjbrooks** [spacetelescope/webbpsf#342]
@obi-wan76 notified me that the current output of the `Simulated OTE Mirror Move Demo.ipynb` shows an error that clearly has to do with my account so in trying to run a clean version of the notebook I found that under the JSC OTIS Test Configurations section, `webbpsf` is trying to find the file `jwst_pupil_JSC_OTIS_Cryo.fits` in `webbpsf-data`, the file seems to not exist in `webbpsf-data`.

**Comment by mperrin** [comment]
We should delete that part of the notebook. I don't see any reason to try to maintain the JSC OTIS part of the simulator any more (and it never worked super well to begin with).

**Comment by kjbrooks** [comment]
Sounds good. I can go ahead and fix that.

**Comment by kjbrooks** [comment]
Closed by #343
