### ISSUE TITLE
Change mask file MASK_NRM.fits.gz used for NIRISS AMI PSFs

### ISSUE THREAD

**Issue by rcooper295** [spacetelescope/webbpsf#373]
I made a new version of the pupil mask image to be used for NIRISS AMI PSFs. I have tested this file with WebbPSF by replacing the existing file in the webbpsf-data/NIRISS/optics directory of the data files and comparing it to the equivalent analytically simulated PSFs (using ImPlaneIA software). I found maximum differences of a few x 10^-5 from the analytically simulated PSFs when both are normalized to have a peak pixel value of unity. The file has the required header keywords (plus additional information in the header) to work with WebbPSF.

File has been sent to Marshall Perrin via email.

**Comment by marcio-melendez** [comment]
@rcooper295 @mperrin I reviewed the new NRM file and compared to the old one. Great work, it is amazing that such small difference on the edges of the hexagons mask can improve the science goals by that much. I think this could be a great addition to WebbPSF the way it is now, however, I wanted to point out a couple of small details:
1) The new mask is in float32 whereas the old one is float64, does it matter? 
2) The new mask has an author information with a non-functional e-mail (?) "rcooper@witserv1.stsci.edu" perhaps this can be replace with some proper contact information.  
I have some very small comments regarding the JWST- document but I'll send those by e-mail.

**Comment by rcooper295** [comment]
Sorry, this notification got buried in my inbox!
1. I can very easily re-make it as float64 for consistency; I also don't know if it matters. 
2. I used one of the institute's linux servers to run the code that makes it because it is much faster, thus the non-functional email. I'll manually go in and change that to my normal institute email. 
I will send the re-revised mask file to @mperrin (unless it's too late?)
I'm happy to address any additional comments you have about the document (assuming you're referring to the TR I wrote with Anand?) but I don't think I've received anything else by email about it.

**Comment by mperrin** [comment]
Float64 vs float32 will make no significant difference - I don't see any benefit to put any effort into redoing that.   Changing the email address in the file is easy enough, though I would guess anyone who tried emailing you `@witserv1` could easily enough guess the correct address without much difficulty. If you do want to change that then feel free to email the updated file to me or Marcio, or just put it somewhere on central store and comment here with the path. Thanks

**Comment by rcooper295** [comment]
I changed the author name and put the file at:
/ifs/jwst/wit/niriss/rcooper/MASK_NRM.fits.gz
Thanks!

**Comment by mperrin** [comment]
@obi-wan76 to follow up on this from last year, did @rcooper295's updated NRM mask ever make it into the webbpsf-data-source directory on central store?

**Comment by mperrin** [comment]
@obi-wan76 to follow up on this from last year, did @rcooper295's updated NRM mask ever make it into the webbpsf-data-source directory on central store?

**Comment by rcooper295** [comment]
I just checked the file at /grp/jwst/ote/webbpsf-data/NIRISS/optics/MASK_NRM.fits.gz and it is still the older version. I'm giving a short presentation about this at TIPS this week, so if at all possible it would be great to be able to say that the file is available for general use.

**Comment by marcio-melendez** [comment]
@rcooper295 I don't have access to the file, under /ifs/jwst/wit/niriss/rcooper/MASK_NRM.fits.gz. In particular, I don't have access to /ifs/jwst/wit/niriss/. Can you share it some place else? Box? I can review and then copy to /grp/jwst/ote/webbpsf-data/NIRISS/optics/
Thanks!

**Comment by rcooper295** [comment]
I just shared the file on Box via your Institute email address, let me know if you are still unable to access it!

**Comment by marcio-melendez** [comment]
Hi @rcooper295, 
The file looks great. I am waiting from ITSD to grant me permission to write into /grp/jwst/ote/webbpsf-data/NIRISS/optics; As soon as I get it, I'll replace the mask. 
Thanks!

**Comment by marcio-melendez** [comment]
@rcooper295 I just updated the file under /grp/jwst/ote/webbpsf-data/NIRISS/optics/ . It is also updated in our data folder, thus it will be included in the next data product release for users outside stsci.
 
Thanks for this work and I apologized for the long waiting time.
