### ISSUE TITLE
Have a way to suppress the data files missing error message

### ISSUE THREAD

**Issue by eteq** [spacetelescope/webbpsf#380]
This is probably related to #266, but I didn't see it explicitly so I'm raising it as a distinct issue:

When I do, say, the following:
```
from webbpsf import NIRSpec
instrument = NIRSpec()
```

I get an `OSError` about the data files being missing, which is quite sensible.  However, at the same time *even if I catch the exception*, I see a big ``***********  ERROR  ******  ERROR  ******  ERROR  ******  ERROR  ***********`` message.  This is problematic because it means downstream applications can't check for this error and do the download as needed.  It doesn't seem like this is at all clear because the error gets printed as `stderr.write(...)`, bypassing any possible catching mechanisms. 

Several solutions come to mind of varying complexity, but I think the easiest is simply to include this error message as part of the `OSError` instead of a separate error message.  The user will still then see the error (and it normally goes to stderr), but catching the exception will supress it.

**Comment by mperrin** [comment]
Agreed! Good suggestion. Seems reasonable to include this text in with the exception as you suggest.
