### ISSUE TITLE
Broken link to thermal slew notebook in version history in read the docs

### ISSUE THREAD

**Issue by kjbrooks** [spacetelescope/webbpsf#381]
Laurent Pueyo pointed out to me that the link to the notebook for calculating the OPDs for a thermal slew change is broken on this page:  https://webbpsf.readthedocs.io/en/latest/relnotes.html?highlight=thermal_slew#version-0-9-0

It looks like the link given does not include the special characters to indicate spaces between each word. 
This is the link given: https://github.com/spacetelescope/webbpsf/blob/stable/notebooks/ExampleConstructionofOPDsfromDeltaTimeAfterSlew.ipynb
This is the actual link: https://github.com/spacetelescope/webbpsf/blob/stable/notebooks/Example%20Construction%20of%20OPDs%20from%20Delta%20Time%20After%20Slew.ipynb

**Comment by mperrin** [comment]
@kjbrooks can you pull request in the fix for this, please? Or else @shanosborne? Thanks much.
