### ISSUE TITLE
Deprecate jwxml

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/webbpsf#386]
See https://github.com/mperrin/jwxml/issues/14 where I propose deprecating the old jwxml package and moving part of its code into webbpsf: 

> Having to fix something in this package (in PR #13) makes me realize how outdated and overtaken by events this whole package is. All the SIAF parts have been migrated to pysiaf and superseded by improved/updated versions there. (pysiaf was started in 2018; the last time this package was touched was 2017). The only other code of interest here is the SUR parsing. We should probably just move that code to webbpsf in a future release, and entirely get rid of this package.
> Furthermore, formally speaking functional code ought to be in a repo under spacetelescope not just in my own personal github space. I never got around to move it over since we haven't edited this in years and I just never thought of it. But it's not worth moving and maintaining this repo for only ~100 lines of SUR parsing code.
> Proposal:
> - We migrate jwxml/mirrors.py to webbpsf/surs.py and update the code in WebbPSF and elsewhere accordingly.
> - We remove the dependency of webbpsf on jwxml.
> - We mark this repository jwxml as deprecated, and update the README to point people at pysiaf and webbpsf instead.
> - No future development/support on this repo is needed.
> - @shanosborne @Skyhawk172 do you concur?

Historical note - the jwxml code actually originally started out here in webbpsf (commit 377d135, back in 2013), then over time got split out to a submodule, then eventually to its own package (PR #136 back in 2016). We did that because the SIAF parsing code was useful outside of just webbpsf. Then Johannes took my SIAF parsing code, built on it and greatly expanded it to make `pysiaf` starting in 2018, which supersedes any need for the SIAF code in jwxml. So by bringing the SUR code back into webbpsf, it'll be coming full circle. 

@shanosborne would you be willing to take the lead in these updates in webbpsf, please?

**Comment by Skyhawk172** [comment]
That makes sense to me. I concur.

**Comment by shanosborne** [comment]
@mperrin Yes I can work on this. What time frame were you thinking of for getting this implemented?

**Comment by mperrin** [comment]
It’s not urgent but it’s also a relatively small scope task, so no reason to let it drag out too long. Within this next month?
