### ISSUE TITLE
Coma/distortion observed in Global Alignment (single-segment mode)

### ISSUE THREAD

**Issue by Skyhawk172** [spacetelescope/webbpsf#387]
Observed a slight coma / distortion rather than maintaining GA image array shape perfectly. Hypothesis - result of oversimplification in MIRAGE psf gen for the segment offsets due to SM motion.

**Comment by mperrin** [comment]
This will be addressed in improvements in Webbpsf to save the piston, tip, tilt Zernike terms as header keywords (to be rolled into #378), and improvements in MIRAGE psfs/segment_psfs to use those rather than the segment pose tilts in X, Y only.

**Comment by mperrin** [comment]
@Skyhawk172 can you confirm that this is fixed now? Via the combination of #392 and #398, and the associated PR in MIRAGE to use the updated header keywords for segment positions.

**Comment by mperrin** [comment]
@Skyhawk172 can you confirm that this is fixed now? Via the combination of #392 and #398, and the associated PR in MIRAGE to use the updated header keywords for segment positions.

**Comment by Skyhawk172** [comment]
Just to refresh my memory: this was observed when we moved the SM back and forth across nominal focus?  I can re-run a  subset of these observation to confirm we don't imprint coma/distortion onto those exposures.
