### ISSUE TITLE
object has no attribute '_extra_keywords'

### ISSUE THREAD

**Issue by JarronL** [spacetelescope/webbpsf#411]
When trying run a very basic PSF calculation, `inst = webbpsf.MIRI(); hdul = inst.calc_psf()` (or any other instrument), WebbPSF chokes with the following error:

```python

~/GitHub/webbpsf/webbpsf/webbpsf_core.py in _get_fits_header(self, result, options)
    351         result[0].header['DET_Y'] = (dpos[1], "Detector Y pixel position of array center")
    352 
--> 353         for key in self._extra_keywords:
    354             result[0].header[key] = self._extra_keywords[key]
    355 

AttributeError: 'MIRI' object has no attribute '_extra_keywords'
```

The issue appears to be that that `self._extra_keywords` dictionary never gets created. This property gets instantiated within the `get_optical_system()` method: https://github.com/spacetelescope/webbpsf/blob/fa1c1044445162a41aac3405873207266edfe1bb/webbpsf/webbpsf_core.py#L407

If I manually call `get_optical_system()`, then the PSF calculation works without issue. 

I am running poppy v0.9.0 and webbpsf v0.9.1.dev93+ga065f01

**Comment by JarronL** [comment]
> I am running poppy v0.9.0 and webbpsf v0.9.1.dev93+ga065f01

Doing a little more sleuthing, it looks like this is related to `_get_optical_system` being deprecated in the development version of both poppy and webbpsf in favor of `get_optical_system`. The development version of webbpsf sets `self._extra_keywords` within `get_optical_system`, but this function will never get called in my case, because the stable version of poppy's `calc_psf` function uses `_get_optical_system`.

So, I guess my take away is that I should always pair the development version of poppy and webbpsf..

**Comment by JarronL** [comment]
I think this somehow has to do with how `_get_optical_system` is being deprecated and the way in which one function calls the other, specifically related to the different versions (stable vs development). There's a subtlety here that I'm not quite understanding.

In any case, if I duplicate this code from poppy dev:
```python
    def _get_optical_system(self, *args, **kwargs):
        """ Return an OpticalSystem instance corresponding to the instrument as currently configured.
        """
        # Note, this has historically been an internal private API function (starting with an underscore)
        # As of version 0.9 it is promoted to a public part of the API for the Instrument class and subclasses.
        # Here we ensure the prior version works, back compatibly.
        import warnings
        warnings.warn("_get_optical_system is deprecated; use get_optical_system (without leading underscore) instead.",
                      DeprecationWarning)
        return self.get_optical_system(*args, **kwargs)
```

and place it in webbpsf's `SpaceTelescopeInstrument` class, the issue goes away.

**Comment by mperrin** [comment]
Hi Jarron, the short answer is please upgrade to poppy 0.9.2 the current release. That’s what’s needed for the dev version of WebbPSF.

**Comment by JarronL** [comment]
Yup, that worked. Thanks!
