### ISSUE TITLE
WebbPSF model for MIRI "cross artifact" appears low compared to CDP

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/webbpsf#415]
The MIRI cross artifact (detector internal scattering effect) model in WebbPSF appears to be substantially lower than what's shown in the CDP PSFs. See plots below.  Found this in the course of modifying MIRISim to work with WebbPSF for OTE commissioning sims. 

This is mostly relevant for the shorter wavelength PSFs (so, less relevant for coronagraphic science with MIRI but very relevant to OTE commissioning uses of MIRI which are mostly in F560W where this effect is strongest). 

The [code in webbpsf](https://github.com/spacetelescope/webbpsf/blob/develop/webbpsf/distortion.py#L306) is based on Alistair's tech report MIRI-TN-00076-ATC_Imager_PSF_Issue_4.pdf, which gives an IDL model for this effect, which we ported to Python. I can't remember now what cross checking we did at the time. (@shanosborne, any chance you have any recollection or notes on this?).  This doesn't use the [much higher fidelity GPU model](https://github.com/merope82/GimMIRI) by @merope82. 

Seems surprising to me that no one on the MIRI team has noticed or commented on this before... surely someone has done this comparison before me?  @JarronL, @merope82, @swolff9 - have any of you perhaps looked at this, or know of others who might have? 

Is Alistair's tech report still the best reference for this? Is there some other documentation of what was assumed in the CDP PSFs? Updating the model parameters in webbpsf would be easy, if we can get guidance as to what the appropriate values are. Or shall I just empirically adjust the amplitude until it matches the CDP PSFs? 

![Unknown](https://user-images.githubusercontent.com/1151745/109010387-b4214180-767d-11eb-86b8-6e6962aec20e.png)
![Unknown-1](https://user-images.githubusercontent.com/1151745/109010393-b6839b80-767d-11eb-9b60-8f8ac33c90a8.png)

**Comment by mperrin** [comment]
Code for the above plots:

```python
webbpsf_psfs = {}
mir = webbpsf.MIRI()
mir.pupilopd = 'OPD_RevW_ote_for_MIRI_predicted.fits.gz'
for i, filt_wl in enumerate([560, 770, 1000]):

    mir.filter = f"F{filt_wl}W"
    webbpsf_psfs[filt_wl] = mir.calc_psf(fov_pixels=128, oversample=4)


vmin=1e-4

fig, axes = plt.subplots(figsize=(10,14), ncols=2, nrows=3, gridspec_kw={'width_ratios':[1,1]})
fig.subplots_adjust(hspace=0.3) #, gridspec_kwargs={'hspace':0.2})

for i, filt_wl in enumerate([560, 770, 1000]):
    psf_fn = f'/Users/mperrin/data/mirisim/CDP/MIRI_FM_MIRIMAGE_F{filt_wl}W_PSF_07.02.00.fits'
    psf_data = fits.getdata(psf_fn)[0]
    axes[i,0].imshow(psf_data, norm = matplotlib.colors.LogNorm(vmin, 1), 
                    cmap=poppy.conf.cmap_sequential)
    axes[i,0].set_title(os.path.basename(psf_fn))
    
    webbpsf.display_psf(webbpsf_psfs[filt_wl], ext=2, ax=axes[i,1], 
                        normalize='peak', vmin=vmin, vmax=1,
                       title=f'WebbPSF Sim for F{filt_wl}W')
    axes[i,1].xaxis.set_visible(False)
    
colors=['C0', 'C1', 'C3']

fig, axes = plt.subplots(figsize=(10,14), ncols=1, nrows=3)


for i, filt_wl in enumerate([560, 770, 1000]):
    psf_fn = f'/Users/mperrin/data/mirisim/CDP/MIRI_FM_MIRIMAGE_F{filt_wl}W_PSF_07.02.00.fits'
    psf_data = fits.getdata(psf_fn)[0]
    
    axes[i].semilogy(psf_data[256], label=f"F{filt_wl}W, CDP", color=colors[i])

    webbpsf_normalized = webbpsf_psfs[filt_wl][2].data.copy()
    webbpsf_normalized /= webbpsf_normalized.max()
    axes[i].semilogy(webbpsf_normalized[256], label=f"F{filt_wl}W, WebbPSF",
                 color=colors[i], ls='--')
    
    axes[i].legend()
    axes[i].set_ylabel("Cut along X axis")
    axes[i].set_xlabel("Pixel coordinate")
        
```

**Comment by mperrin** [comment]
Empirical correction factors to make WebbPSF agree with the CDP PSFs: 
F560W: 3.587
F770W: 3.392
F1000W: 2.100
F1130W: 1.288
F1280W: 1.403

(The model amplitude is listed as 0 for all longer filters)

I have also just verified that if I compare cuts that _aren't_ right along the X axis (i.e. shifted up or down to avoid the bright part of the cross) then the CDP PSF and WebbPSF are in very good agreement. So the disagreement is indeed just the cross.

**Comment by merope82** [comment]
Hi Marshall,

Alistair's estimates were really preliminary. George probably knows more
about the history of the modeling. You should check out our new paper on
the cross artifact. I was planning on running a large simulation and
generating more PSFs. I'll put it on my must to do list.

-A

**Comment by merope82** [comment]
Yes, we (Andras) can do better. However, it is important to understand the
time frame for getting improvements in as well as the fidelity needed.

- George

On Wed, Feb 24, 2021 at 7:51 AM Andras Gaspar <agaspar@arizona.edu> wrote:

> Hi Marshall,
>
> Alistair's estimates were really preliminary. George probably knows more
> about the history of the modeling. You should check out our new paper on
> the cross artifact. I was planning on running a large simulation and
> generating more PSFs. I'll put it on my must to do list.
>
> -A
>
> On Wed, Feb 24, 2021 at 6:54 AM Marshall Perrin <notifications@github.com>
> wrote:
>
>> *External Email*
>>
>> The MIRI cross artifact (detector internal scattering effect) model in
>> WebbPSF appears to be substantially lower than what's shown in the CDP
>> PSFs. See plots below. Found this in the course of modifying MIRISim to
>> work with WebbPSF for OTE commissioning sims.
>>
>> This is mostly relevant for the shorter wavelength PSFs (so, less
>> relevant for coronagraphic science with MIRI but very relevant to OTE
>> commissioning uses of MIRI which are mostly in F560W where this effect is
>> strongest).
>>
>> The code in webbpsf is based on Alistair's tech report
>> MIRI-TN-00076-ATC_Imager_PSF_Issue_4.pdf, which gives an IDL model for this
>> effect, which we ported to Python. I can't remember now what cross checking
>> we did at the time. (@shanosborne, any chance you have any recollection
>> or notes on this?). This doesn't use the much higher fidelity GPU model
>> by @merope82.
>>
>> Seems surprising to me that no one on the MIRI team has noticed or
>> commented on this before... surely someone has done this comparison before
>> me? @JarronL, @merope82, @swolff9 - have any of you perhaps looked at
>> this, or know of others who might have?
>>
>> Is Alistair's tech report still the best reference for this? Is there
>> some other documentation of what was assumed in the CDP PSFs? Updating the
>> model parameters in webbpsf would be easy, if we can get guidance as to
>> what the appropriate values are. Or shall I just empirically adjust the
>> amplitude until it matches the CDP PSFs?
>>
>> [image: Unknown]
>> [image: Unknown-1]
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub, or unsubscribe.
>>
>

-- 
George Rieke
Regents Professor of Astronomy and Planetary Sciences
The University of Arizona
933 N. Cherry Ave.
Tucson, AZ 85721
520-621-2832

**Comment by mperrin** [comment]
In the short term (this week and next) we're working on simulations for the upcoming MIMF KDP practice, including the MIMF sensing data and PSF check data which for MIRI are both in F560W. Whether we want to try to improve this in any way before then, you all can tell me - If you (and/or Alistair) concur that what's currently in WebbPSF is sufficient for the purposes of that KDP, then no action needed now. 

It would be very straightforward to scale up the model in WebbPSF to match the CDP data products, if you concur those are reliable and the best reference, or to scale the up to match either your models or the CV2 PSFs as shown in your paper. What do you consider the most reliable reference for these? I'd assume we should take the CV2 PSFs as the ground truth? 

In terms of fidelity needed, again I'd say that you can probably better advise what we should be aiming for. What will be most useful in helping prepare to model and interpret commissioning data? 

Right now the cross artifact is off by ~3x in WebbPSF vs CDP; it's obviously coarsely discrepant (if we take the CDP as correct). I'd think if we get it within 50% that is good enough for many purposes; by the time we are doing PSF fitting analyses that are dependent on very high fidelity PSF models within <10% or much better, all this will be obsolete and we'll be much better informed based on extensive in flight data.

**Comment by mperrin** [comment]
(BTW, is George on Github? Should we take this to email and loop him in, or are you happy to continue the discussion here?)

**Comment by mperrin** [comment]
For my own reference here's a link to Andras' paper mentioned above: https://ui.adsabs.harvard.edu/abs/2021PASP..133a4504G/abstract
