### ISSUE TITLE
Migrate CI to somewhere other than Travis?

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/webbpsf#453]
@shanosborne - is there yet any clarity or direction from INS or elsewhere within ST about what the recommended/preferred CI platform should be, after Travis shuts down the free version?

**Comment by shanosborne** [comment]
@mperrin, I have still heard no official announcement. Some people have said that Github actions will most likely be the recommendation, but that's not from anyone actually involved in making the decisions. I think we can probably switch over to actions and expect that it will be okay, it's up to us.

**Comment by mperrin** [comment]
Done via #455
