### ISSUE TITLE
Segment mask file name convention mismatch between opds.py and central store directory

### ISSUE THREAD

**Issue by aggle** [spacetelescope/webbpsf#460]
In `opds.py`, the OPD class expects a segment mask file of the form `JWpupil_segments_RevW_npix{self.npix}.fits.gz`. On central store, these are kept in the folder `/grp/jwst/ote/webbpsf-data/` (which is what I have for WEBBPSF_PATH) but have the naming convention `jwst_pupil_RevW_npix{NNN}.fits.gz`. The timestamp on the `jwst_pupil*` files all comes from May 14; is it possible that this is just a typo and the files should start with `JWpupil`?

**Comment by mperrin** [comment]
Recent changes in this part of the code and data, which have not yet been fully released. @kjbrooks or @obi-wan76 can you help @aggle get this sorted out, please?   There should be _both_ `jwst_pupil_[etc]` and `JWpupil_segments_[etc]` files in the data folders.

**Comment by mperrin** [comment]
FYI to Jonathan @aggle: The `jwst_pupil` files are overall "which pixels are transmissive or not in the pupil?". The `JWpupil_segments` files are more specific "which pixels are this one particular segment number N, for N from 1-18?"

**Comment by kjbrooks** [comment]
@aggle Did Marshall answer this issue for you, or did you have an error when running code?  To expand on what Marshall said, the `JWpupil_segments` files are the JWST pupil but with each segment filled with a different number, that number helps us identify the different segments. The `jwst_pupil` files are a JWST pupil mask, where the segments are all ones, and the gaps, struts, and surrounding areas are zeros. Each of the files are needed for different uses within WebbPSF.

I can see the following files in the location that you gave, which is as we expect:
- `JWpupil_segments_RevW_npix4096.fits.gz`
- `JWpupil_segments_RevW_npix2048.fits.g`
- `JWpupil_segments_RevW_npix1024.fits.gz`
- `jwst_pupil_RevW_npix4096.fits.gz`
- `jwst_pupil_RevW_npix2048.fits.gz`
- `jwst_pupil_RevW_npix16384.fits.gz`
- `jwst_pupil_RevW_npix1024.fits.gz`

Do you see something different?

**Comment by aggle** [comment]
Thanks for the explanations! I see that they JWpupil* files are there now (looks like they were created yesterday). Apologies for the commotion.

Jonathan

From: Keira Brooks ***@***.***>
Reply-To: spacetelescope/webbpsf ***@***.***>
Date: Wednesday, May 26, 2021 at 5:03 PM
To: spacetelescope/webbpsf ***@***.***>
Cc: Jonathan Aguilar ***@***.***>, Mention ***@***.***>
Subject: Re: [spacetelescope/webbpsf] Segment mask file name convention mismatch between opds.py and central store directory (#460)


@aggle<https://urldefense.com/v3/__https:/github.com/aggle__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!jplytaQY7TOjIpKm_Qj7zDpqyu-MpBEbCOntIEQa7DVrktL8XLdwL2DUadwawDAN$> Did Marshall answer this issue for you, or did you have an error when running code? To expand on what Marshall said, the JWpupil_segments files are the JWST pupil but with each segment filled with a different number, that number helps us identify the different segments. The jwst_pupil files are a JWST pupil mask, where the segments are all ones, and the gaps, struts, and surrounding areas are zeros. Each of the files are needed for different uses within WebbPSF.

I can see the following files in the location that you gave, which is as we expect:

  *   JWpupil_segments_RevW_npix4096.fits.gz
  *   JWpupil_segments_RevW_npix2048.fits.g
  *   JWpupil_segments_RevW_npix1024.fits.gz
  *   jwst_pupil_RevW_npix4096.fits.gz
  *   jwst_pupil_RevW_npix2048.fits.gz
  *   jwst_pupil_RevW_npix16384.fits.gz
  *   jwst_pupil_RevW_npix1024.fits.gz

Do you see something different?

**Comment by shanosborne** [comment]
@aggle @kjbrooks - To add some clarity, you were right when you submitted this ticket that those files were missing. But in a fun coincidence, yesterday I was un-relatedly updating the data in the `/grp/jwst/ote/webbpsf-data/` central store location and added those files. 

If you find that any other data files are missing or are causing problems, please let me know and we'll get them sorted out.

**Comment by JarronL** [comment]
@shanosborne Do these files exist somewhere publicly? I've been running the development versions of webbpsf on my local machine, so it might be useful to get pre-release access to these files? Currently in my `webbpsf_data` directory:

JWpupil_segments_RevW_npix1024.fits
JWpupil_segments.fits

jwst_pupil_RevW_npix1024.fits.gz
jwst_pupil_RevW_npix2048.fits.gz
jwst_pupil_RevW_npix16384.fits.gz

**Comment by shanosborne** [comment]
Hi @JarronL, Yes you should be able to get the new data from here: https://stsci.box.com/s/g8nq6j1lk10ml7tyxxn28rbl40h1zky2
