### ISSUE TITLE
WebbPSF-Roman Cycle 9 Update

### ISSUE THREAD

**Issue by robelgeda** [spacetelescope/webbpsf#465]
WebbPSF Data:

- [x] Update new Zernike phase NOLL coefficients
    - [x] WFI - (Sheet Tab:  `WIM`)
    - [x] GRISM - (Sheet Tab:  `WIM-GRISM`)
    - [x] PRISM - (Sheet Tab:  `WIM-PRISM`)

- [x] New filter called the K filter (Sub-issue #403)

- [x] Filter bandpass info.

- [x] Update Pupil Masks
    - [x] Each SCA has its own copy 
    - [x] 4 types of masks (Prism and Grism have their own Pupils now)

WebbPSF Code:

- [x] Pupil controller 
- [x] Tests 
- [x] Docs
    - [x] Add the following to docs "The jitter for the Roman observatory is 0.012 arcsec per axes"

Checks:

- [x] Instrument layout diagram (currently outdated in the ref file)
- [x] Design numbers (have not been checked for a while)

**Comment by robelgeda** [comment]
Histogram of Wavelengths and number of data points
```
{0.48: 90,
 0.62: 90,
 0.76: 180,
 0.869: 90,
 0.927: 180,
 0.977: 90,
 1.06: 90,
 1.131: 90,
 1.192: 90,
 1.293: 90,
 1.38: 90,
 1.454: 90,
 1.464: 90,
 1.577: 90,
 1.683: 90,
 1.774: 90,
 1.842: 90,
 1.95: 90,
 2.0: 180,
 2.125: 90,
 2.3: 90}
```

 `0.76,  0.927,  2.0` are repeated

**Comment by ojustino** [comment]
Comments after meetups:
- We had questions about the total number of WIM Zernike entries (detailed in @robelgeda's previous post).
- New SCA range has changed ("SCA Position" columns); we should check if this necessitates new code.

**Comment by robelgeda** [comment]
The Zernike wavelength range is not covering the new filter
