### ISSUE TITLE
Warn users about missing data or using WFIRSTImager

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/webbpsf#49]
<a href="https://github.com/josePhoenix"><img src="https://avatars3.githubusercontent.com/u/172886?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [josePhoenix](https://github.com/josePhoenix)**
_Thursday Feb 19, 2015 at 21:56 GMT_
_Originally opened as https://github.com/mperrin/webbpsf/pull/49_

----

Last two changes pre-release: add disclaimer to WFIRST classes, improve user experience in the absence of WEBBPSF_DATA cc @mperrin @cslocum 

----

_**[josePhoenix](https://github.com/josePhoenix)** included the following code: https://github.com/mperrin/webbpsf/pull/49/commits_

**Comment by mperrin** [comment]
<a href="https://github.com/mperrin"><img src="https://avatars0.githubusercontent.com/u/1151745?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mperrin](https://github.com/mperrin)**
_Thursday Feb 19, 2015 at 23:03 GMT_

----

Hmm, so I went ahead and merged this. But now I see that it has the side effect of suppressing the exception in whatever program or module is trying to import webbpsf. Wouldn't it be better to pass the exception up higher so that the program that just tried the import knows it cannot continue? 

I guess I don't understand entirely the motivation for calling traceback.print_exc() in this context instead of just letting the exception percolate upwards? 

Example: 

```
mperrin@peregrine ~ > unsetenv WEBBPSF_PATH
mperrin@peregrine ~ > ipython
Python 2.7.8 (default, Oct  7 2014, 15:36:11)
...

In [1]: try:
   ...:     import webbpsf
   ...:     print "OK"
   ...: except:
   ...:     print "Not OK :-("
   ...:
WebbPSF log messages of level INFO and above will be shown.
WebbPSF log outputs will be directed to the screen.
Traceback (most recent call last):
  File "/Users/mperrin/Dropbox (Personal)/Documents/software/webbpsf/webbpsf/__init__.py", line 93, in <module>
    utils.get_webbpsf_data_path()
  File "/Users/mperrin/Dropbox (Personal)/Documents/software/webbpsf/webbpsf/utils.py", line 143, in get_webbpsf_data_path
    raise EnvironmentError("Environment variable $WEBBPSF_PATH is not set!")
EnvironmentError: Environment variable $WEBBPSF_PATH is not set!

 *********  ERROR  ******  ERROR  ******  ERROR  ******  ERROR  *************
 *                                                                          *
 *  WebbPSF requires several data files to operate.                         *
 *  These files could not be located automatically at this                  *
 *  time. Please download them to a location of your                        *
 *  choosing and either                                                     *
 *   - set the environment variable $WEBBPSF_PATH to point there, or        *
 *   - set the WEBBPSF_PATH variable in your webbpsf.cfg config file        *
 *     (probably in ~/.astropy/config/ or similar location)                 *
 *                                                                          *
 *  See http://pythonhosted.org/webbpsf/installation.html, under            *
 *  "Installing the Required Data Files", for more details.                 *
 *  WebbPSF will not be able to function properly until this has been done. *
 *                                                                          *
 ****************************************************************************
OK

```

Note that the import case in the try was successful, as indicated by the print OK.

**Comment by mperrin** [comment]
<a href="https://github.com/josePhoenix"><img src="https://avatars3.githubusercontent.com/u/172886?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [josePhoenix](https://github.com/josePhoenix)**
_Friday Feb 20, 2015 at 00:20 GMT_

----

Oh, whoops. I noticed Christine didn't read the notice and gravitated straight to the traceback, so I figured I'd reorder them. But, that has the unintended consequence you identified!

Better fix that.

**Comment by mperrin** [comment]
<a href="https://github.com/josePhoenix"><img src="https://avatars3.githubusercontent.com/u/172886?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [josePhoenix](https://github.com/josePhoenix)**
_Friday Feb 20, 2015 at 00:26 GMT_

----

Also, apparently GitHub emails are arriving delayed by an hour.

**Comment by cslocum** [comment]
Wow - you guys are revisiting some old stuff!  My memory of what I did three years ago is rusty, but let me know if you need anything.

**Comment by mperrin** [comment]
Hi @cslocum again this is just an automated script copying *all* issues from `mperrin/webbpsf` into `spacetelescope/webbpsf`. It's just part of migrating all this stuff from my personal space into the `spacetelescope` organization space.   

No action needed from you now!
