### ISSUE TITLE
Installing via pip

### ISSUE THREAD

**Issue by Vikramb1** [spacetelescope/webbpsf#562]
I have tried to install webbpsf via pip, however I can seem to get the tar file recognized using wsl. I exported and stored it here: mnt/c\Users\vikra\webbpsftest. On wsl, I then did this:  export WEBBPSF_PATH=$HOME/webbpsftest/webbpsf-data. When I cd to When I type echo $WEBBPSF_PATH it is showing the correct path. However when I try and import the module I get an error that I am missing the data files. Is there a solution to this? Thanks.

**Comment by mperrin** [comment]
Apologies but I don't have any detailed insight into what might be going on. I don't have any direct experience with using WebbPSF in WSL on Windows.  @ojustino see the error message in this issue, please. Any chance you might have any insights into how to set this up with the environment variables in that context?

**Comment by mperrin** [comment]
Hi, I wanted to follow up on this old issue from last summer. @Vikramb1, were you ever able to get this installed using WSL? Do. you still want or need further assistance with this?

**Comment by Vikramb1** [comment]
> Hi, I wanted to follow up on this old issue from last summer. @Vikramb1, were you ever able to get this installed using WSL? Do. you still want or need further assistance with this?

Hi, I did end up getting this to work, thanks.
