### ISSUE TITLE
Empirical PSFs?

### ISSUE THREAD

**Issue by keflavich** [spacetelescope/webbpsf#568]
Is there any plan to include on-sky / in-orbit PSFs into WebbPSF?  Looking at some of the early release data, I see significant differences between the effective PSF and the theoretical ones here, which I think is expected. I'd like to know if there are better PSFs available than what I derived from an image.

**Comment by mperrin** [comment]
Hi @keflavich - please see this page for examples of using some recently-added code to access flight wavefront sensing data, and get better matched simulations contemporaneous to any particular science data:
https://webbpsf.readthedocs.io/en/latest/jwst_measured_opds.html

For now this requires using the latest development version of WebbPSF from GitHub. This plus some other additions will end up in the next release, likely ~September-ish.

**Comment by keflavich** [comment]
That's perfect.  I just failed to find that... I think because I didn't realize what OPDs are so I ignored that item in the sidebar.
