### ISSUE TITLE
Write & read calculated PSFs?

### ISSUE THREAD

**Issue by keflavich** [spacetelescope/webbpsf#570]
Is there a way to serialize and read back in calculated PSFs?  I don't see any read mechanisms in the docs, and the write mechanism seems to be limited to single PSF models, not grids.

This question may apply more generally to photutils GridPSF models, but it would be useful here as the PSF calculations take a non-negligible amount of time to run (not too long, but not zero either).

**Comment by mperrin** [comment]
Sure! For single PSFs, they're returned as FITS HDUList objects, so can be written & read back in just like any other FITS file, sure.

Similarly there's  code for exporting and reloading gridded PSF models. See example code in https://github.com/spacetelescope/webbpsf/blob/stable/notebooks/Gridded_PSF_Library.ipynb under the section heading "Saving Files". 

Hope that helps!

**Comment by keflavich** [comment]
Again, perfect!  I'm glad this is something you thought of.  I didn't find it in the docs by searching for 'read', 'write', or 'serialize' - it might help to index this.  But on the other hand, this issue ought to turn up on google next time I want to ask the same question.
