### ISSUE TITLE
No attribute of load_wss_opd_by_date?

### ISSUE THREAD

**Issue by abiglee7** [spacetelescope/webbpsf#572]
Hi! When I try to run the code example here: https://webbpsf.readthedocs.io/en/latest/jwst_measured_opds.html

I get the error:
`AttributeError: 'NIRCam' object has no attribute 'load_wss_opd_by_date'
`

Any tips on how to mitigate this?

**Comment by marcio-melendez** [comment]
You need to make sure you are running the develop branch of WebbPSF, the function is inside webbpsf_core, line 1574:
https://github.com/spacetelescope/webbpsf/blob/develop/webbpsf/webbpsf_core.py#L1574
To check your installation, if you do `dir(nrc)`, you should see the following functions:
`load_wss_opd',
 'load_wss_opd_by_date'
In addition, your installation folder for WebbPSF should have the mast_wss.py file.

**Comment by mperrin** [comment]
Hi! The features to use WSS OPDs are new enough they’re only in the develop branch here on github, not the released version on pypi. My guess is you’re using the released version from pypi? Install the latest from here on GitHub and you should be good to go.

**Comment by abiglee7** [comment]
That worked! Thank you so much.
