### ISSUE TITLE
Add various boolean parameters to bypass downloading OPDs from MAST and use fileName as full filePath

### ISSUE THREAD

**Issue by kulpster85** [spacetelescope/webbpsf#596]
This feature request is to allow external utilities (alternative to MAST Query) to build the opdtable and populate the _fileName_ column with the full file path.  (alternatively a _directory_ column if fileName is used in other ways)

Add a new boolean parameter to toggle the line below from executing and instead just set the full_file_path to the fileName column value.  

`full_file_path = os.path.join(webbpsf.utils.get_webbpsf_data_path(), 'MAST_JWST_WSS_OPDs', row['fileName'])`

Additionally toggle downloading of OPDs from MAST, etc

**Comment by marcio-melendez** [comment]
@kulpster85 this is an old issue, did you add this into a PR? I know there has been some changes to the trending function so, is this issue resolved? Thanks!

**Comment by kulpster85** [comment]
Yeah its been a while haha lemme take a look.

**Comment by kulpster85** [comment]
The toggle is in place: 
```

def wfe_histogram_plot(opdtable, start_date=None, end_date=None, thresh=None, pid=None,
                        download_opds=True, mark_corrections='lines', ote_only=False):
```

**Comment by mperrin** [comment]
Already resolved.
