### ISSUE TITLE
Add opdtable as an optional paramater to monthly_trending_plot()

### ISSUE THREAD

**Issue by kulpster85** [spacetelescope/webbpsf#597]
This feature request is to allow external utilities (alternative to MAST Query) to utilize the monthly trending plot to pass in the opdtable as a parameter to _monthly_trending_plot_.

`def monthly_trending_plot(year, month, verbose=True, instrument='NIRCam', filter='F200W', vmax=200):`

This feature request would allow the opdtable to be provided which would contain the OPD file paths to circumvent calls under the hood that use the Mast Query API within WebbPSF:

webbpsf/trending.py:814
`inst.load_wss_opd(opd_fn, verbose=verbose)` 
webbpsf/webbpsf_core.py:1446
`filename = webbpsf.mast_wss.mast_retrieve_opd(filename, output_path = output_path, verbose=verbose)`

**Comment by Skyhawk172** [comment]
It looks like this has already been taken care of; in `monthly_trending_plot`, I now see a function parameter for `opdtable`.

@kulpster85 can you confirm this does it for your request?

**Comment by kulpster85** [comment]
Yes confirmed:
`def monthly_trending_plot(year, month, verbose=True, instrument='NIRCam', filter='F200W', vmax=200, opdtable=None):`
