### ISSUE TITLE
Trending wavefront_time_series_plot not properly scaling 

### ISSUE THREAD

**Issue by marcio-melendez** [spacetelescope/webbpsf#616]
The wavefront_time_series_plot in trending.py  is not properly scaling the date axis when using the start_date and end_date parameters. The main issue is the label_visits and label_events, if both are set to False, then the figure has the correct scale. 
![Screen Shot 2022-11-30 at 6 07 56 PM](https://user-images.githubusercontent.com/9635910/204927382-d719b8ea-cfe2-49ba-9d84-f1adbe85f0c2.png)
With False for both labels display
![Screen Shot 2022-11-30 at 6 09 55 PM](https://user-images.githubusercontent.com/9635910/204927673-c646ef8d-0256-405c-b08c-3c03b049f480.png)

**Comment by Skyhawk172** [comment]
this is taken care of in [#603](https://github.com/spacetelescope/webbpsf/pull/603)

**Comment by Skyhawk172** [comment]
I confirm that this was taken care of in [#603](https://github.com/spacetelescope/webbpsf/pull/603).

**Comment by marcio-melendez** [comment]
@Skyhawk172 
I installed the latest with the merge of #603 but there is still an issue with labels options in a time range
![image](https://user-images.githubusercontent.com/9635910/205101433-2426f358-e67b-4215-ab3b-fda21908ceae.png)

This is a minor change in both _**if**_ labels to add the end_date as well:
line 146 should be
`if d >= start_date and d_pre.datetime <= end_date:`
and line 166:
`if d_pre.datetime >= start_date and d_pre.datetime <= end_date  and rms < ymax:`
This gives a correct plot with start/end times
![image](https://user-images.githubusercontent.com/9635910/205103417-f4564818-ff5f-4fbb-9afd-1a3b125387ea.png)

I can push a PR with this minor change, I'll add you as reviewer. 

Thanks!

**Comment by marcio-melendez** [comment]
Correction. Line 146 should be `if d >= start_date and d  <= end_date:`

**Comment by mperrin** [comment]
Closed in #621
