### ISSUE TITLE
Add support for MIRI FND for simulating coron TA images

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/webbpsf#628]
I don't understand how/why this wasn't already implemented. It's in the data files. May have just been an oversight accidentally .

**Comment by Skyhawk172** [comment]
I stumbled upon this issue and decided to take a closer look at it. 

It appears the only change that needs to be done is add a line for `FND` in the MIRI `filters.tsv `file, which lives under `webbpsf-data/MIRI/`.  Given the large bandpass of this filter, the minimum number of wavelengths to use should be larger than the other filters, probably ~20.

I ran a quick test by simply adding a line to the MIRI `filters.tsv` file and a PSF is generated without any apparent problem.
I get the following, assuming a flat spectrum covering 8-26 microns:
<img width="478" alt="Screenshot 2023-05-05 at 3 50 15 PM" src="https://user-images.githubusercontent.com/9323123/236556041-c5236f6f-44e7-488c-8b2b-bb6c83311779.png">

The current transmission curve looks like as follow:
![image](https://user-images.githubusercontent.com/9323123/236553395-7ce4d8ca-889e-4e9e-aefc-b73ee0073d9c.png)

I don't know if the `FND.fits` needs to be updated, but it looks a bit noisy at larger wavelengths.

**Comment by Skyhawk172** [comment]
Github won't let me attach a `.tsv` file, so I'll just paste the content here since it's short. To be absolutely clear, this is to replace the `filters.tsv` file under `webbpsf-data/MIRI/`. The only difference is the last line for the neutral density filter (FND):

filter	nlambda
F1000W	9
F1065C	9
F1130W	9
F1140C	9
F1280W	9
F1500W	9
F1550C	9
F1800W	9
F2100W	9
F2300C	9
F2550W	9
F560W	9
F770W	9
FND	20

**Comment by Skyhawk172** [comment]
Marcio gave me the link to where the new webbpsf data reside until the next release (on STScI central store), so I just dropped the updated file there.

**Comment by mperrin** [comment]
This was done as part of release 1.3, and I just re-tested that support for FND exists and works now. Closing this issue.
