### ISSUE TITLE
codecov deprecated and removed

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/webbpsf#658]
Apparently the `codecov` code coverage tool was removed from pypi this morning. See https://github.com/spacetelescope/jwst/pull/7543 

WebbPSF and poppy will need to be updated to remove the dependency on codecov for test coverage, potentially using a similar approach as what's done in the jwst pipeline. (Presumably this will similarly affect any other ST repos also using codecov too?)

FYI @BradleySappington and @obi-wan76

**Comment by BradleySappington** [comment]
@obi-wan76 - I believe @zacharyburnett handled this for many projects including webbpsf and poppy about 2 weeks ago,  I'll handle the review and merge.
https://github.com/spacetelescope/poppy/pull/559
https://github.com/spacetelescope/webbpsf/pull/659
