### ISSUE TITLE
Data files out of date

### ISSUE THREAD

**Issue by JarronL** [spacetelescope/webbpsf#692]
With the release of the latest develop version of webbpsf, I appear to no longer have a valid set of webbpsf-data files:

```
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jarron/NIRCam/webbpsf-data/NIRCam/IPC/KERNEL_IPC_CUBE.fits'
```

Is there an updated pre-release version stashed somewhere that I can grab?

**Comment by marcio-melendez** [comment]
Yes, the Box link is: 
https://stsci.box.com/shared/static/ykkvequ9cbble6qg88ldhjoep4m9ey6x.gz

**Comment by marcio-melendez** [comment]
This was fixed in the stable release
