### ISSUE TITLE
Upcoming incompatibility with dev dependencies

### ISSUE THREAD

**Issue by bmorris3** [spacetelescope/webbpsf#710]
It looks like there may be an upcoming compatibility issue with dev versions of some WebbPSF dependencies. A recent [PR to romancal](https://github.com/spacetelescope/romancal/pull/794) adds a dependency on WebbPSF, and it's [failing on (only) devdeps](https://github.com/spacetelescope/romancal/actions/runs/5802848783/job/15729950130?pr=794#step:10:987). It looks like this line is the offender:

https://github.com/spacetelescope/webbpsf/blob/af28236681c2d311ca8e60d03e8ec5289da81eed/webbpsf/gridded_library.py#L344-L345

The `loc[0]` gets defined in:
```python
loc = np.asarray(loc, dtype=float)
```
and casting it to a string produces, e.g., `np.float64(100.0)`. Later when this gets parsed: 

https://github.com/spacetelescope/webbpsf/blob/af28236681c2d311ca8e60d03e8ec5289da81eed/webbpsf/gridded_library.py#L437-L439

the strings have an unexpected format, which causes `to_model` to crash.

I'm not sure yet which of the devdeps is responsible, but here's the [dev requirements file for romancal](https://github.com/spacetelescope/romancal/blob/main/requirements-dev.txt) that raised this error:
```
git+https://github.com/asdf-format/asdf
git+https://github.com/asdf-format/asdf-transform-schemas
git+https://github.com/asdf-format/asdf-wcs-schemas
--extra-index-url https://pypi.anaconda.org/astropy/simple astropy --pre
git+https://github.com/astropy/asdf-astropy
git+https://github.com/spacetelescope/crds
git+https://github.com/spacetelescope/gwcs
numpy>=0.0.dev0
git+https://github.com/spacetelescope/roman_datamodels@0.17.0
git+https://github.com/spacetelescope/rad@0.17.0
scipy>=0.0.dev0
git+https://github.com/spacetelescope/stpipe
git+https://github.com/spacetelescope/stcal
git+https://github.com/spacetelescope/tweakwcs
```

**Comment by marcio-melendez** [comment]
hi @bmorris3 , we are going to take a look at it. We are currently doing the next stable release of webbpsf v1.2.0. Let me know if the problem persist in stable. If it does, then we'll investigate it further to find a solution. 
Thanks!

**Comment by bmorris3** [comment]
Hi @obi-wan76, this is still an issue for [devdeps tests in romancal](https://github.com/spacetelescope/romancal/actions/runs/6251837848/job/16973829999). Do you have a timeline for v1.2.0?

**Comment by marcio-melendez** [comment]
V1.2.1 is already out, is this still an issue with the latest version of webbpsf? @BradleySappington, any comments?

**Comment by BradleySappington** [comment]
Just took a quick look at the devdeps error, I'm going to assume that 1.2.1 does NOT address this issue (unless @bmorris3 disagrees).

**Comment by BradleySappington** [comment]
@bmorris3, for context, we were mid release when this issue was raised.  I'm planning to spend a few days on webbpsf over the next week or two.

**Comment by BradleySappington** [comment]
@braingram - Adding you as assignee due to #743

**Comment by BradleySappington** [comment]
closing per comment in #743 that says this is fixed with that changeset
