### ISSUE TITLE
Add some more per-instrument specializations in setup_sim_to_match_file

### ISSUE THREAD

**Issue by marcio-melendez** [spacetelescope/webbpsf#726]
First reported by Martha Boyer:
"It appears to just grab the FILTER keyword from the image header and assign that to inst.filter, but that won’t work for images where the filter is in the pupil wheel (e.g., pupil+filter = F164N+F150W2).  In this example, Webbpsf is assigning inst.filter=F150W2, but it should assign inst.filter to F164N."

Further confirm with some of the wavefront sensing observations (WL images) where the combination F212N (filter) and WLM8 (pupil) simulates the F212N filter, not the WL image

**Comment by marcio-melendez** [comment]
from Martha
"webbpsf.setup_sim_to_match_file, but it’s not working because the image headers have PUPIL = MASKBAR & webbpsf says that NIRCam doesn’t have a pupil mask called MASKBAR.  Presumbly webbpsf uses MASKSWB and MASKLWB, but that’s not what’s in the image header"

**Comment by marcio-melendez** [comment]
See #768

**Comment by mperrin** [comment]
This issue shouldn't have been closed in December, since the PR #768 wasn't (and still isn't) merged.

**Comment by mperrin** [comment]
PR #768 was merged in April, so this can be considered closed now.
