### ISSUE TITLE
Add detector effects as default in the oversampled extension 

### ISSUE THREAD

**Issue by marcio-melendez** [spacetelescope/webbpsf#736]
Currently, detector effects are included by default in the detector sampled extension. Detector effects in the oversample PSF can be include via the grid PSF function only. 
We should add detector effects (IPC/charge diffusion) to both extension by default. Note that IPC effects happens in the detector pixels, thus, physically it make sense just to have them included in the detector sample PSF, as currently implemented. However, people are increasingly interested in more realistic oversampled simulations as a way to compare with semi-empirical oversample  PSF from observations.

**Comment by amn3142** [comment]
Yes please, this would be really important for us. Thank you

**Comment by marcio-melendez** [comment]
See #768

**Comment by amn3142** [comment]
Just confirming that if we install the latest develop version it will include this?

**Comment by marcio-melendez** [comment]
Once the PR is merge, it is currently under revision.

**Comment by amn3142** [comment]
If you remember, could you let me know when this gets merged?

**Comment by amn3142** [comment]
Hi @obi-wan76  I was wondering if this was merged? Thanks

**Comment by marcio-melendez** [comment]
@amn3142 This has been merge into dev. #768

**Comment by amn3142** [comment]
@obi-wan76 is there a new webbpsf_data file I need to download to use this feature?

**Comment by marcio-melendez** [comment]
@amn3142 No, you just need to download and install the latest dev branch of WebbPSF. Once you do your simulations you can always check the information inside the fits file header (or the HDUList) to find the parameters for the detector effects. 
Thanks!
