### ISSUE TITLE
Testing against numpy 2.0 and scalar representation changes

### ISSUE THREAD

**Issue by braingram** [spacetelescope/webbpsf#737]
Hi!

The romancal pipeline recently added usage of webbpsf. The romancal tests include testing against the upcoming numpy 2.0 version which includes a change to the string representation of scalar values. See [NEP51](https://numpy.org/neps/nep-0051-scalar-representation.html) for more details but in brief, prior to numpy 2.0:
```
>>> np.float32(3.0)
3.0
```
in numpy 2.0:
```
>>> np.float32(3.0)
np.float32(3.0)
```

I believe this might be causing an issue that can be seen in the romancal development testing job which runs using numpy 2.0:
```python
.tox/py311-devdeps/lib/python3.11/site-packages/webbpsf/gridded_library.py:413: in to_model
    ndd.meta['grid_xypos'] = [((float(ndd.meta[key][0].split(',')[1].split(')')[0])),
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

.0 = <odict_iterator object at 0x7f4d7b4ab970>

>   ndd.meta['grid_xypos'] = [((float(ndd.meta[key][0].split(',')[1].split(')')[0])),
                              (float(ndd.meta[key][0].split(',')[0].split('(')[1])))
                              for key in ndd.meta.keys() if "DET_YX" in key]
E   ValueError: could not convert string to float: ' np.float64(100.0'
```
Full log found here: https://github.com/spacetelescope/romancal/actions/runs/6177529682/job/16768872976?pr=867#step:10:946

It is possible this is the result of an issue in romancal but I wanted to open this issue either way as I did not see testing against numpy 2.0 in this library. Are there plans to enable numpy 2.0 tests in the CI? Thanks!

**Comment by BradleySappington** [comment]
@braingram - Thanks for the talk today.  We will be holding off on CI testing until the release candidate is available. Appreciate all of your insight!

**Comment by braingram** [comment]
@BradleySappington can this be re-opened?

Numpy 2.0 is released.

romancal unit tests show several failures originating in webbpsf:
https://github.com/spacetelescope/romancal/actions/runs/9569032524/job/26380655507?pr=1278#step:10:260
that resemble the following:
```
romancal/lib/tests/test_psf.py:70: in setup_inputs
    psf_model, centroids = create_gridded_psf_model(
romancal/lib/psf.py:181: in create_gridded_psf_model
    gridmodel = inst.create_grid()
.tox/py311-ddtrace-webbpsf/lib/python3.11/site-packages/webbpsf/gridded_library.py:396: in create_grid
    model = self.to_model(psf_arr, meta)
.tox/py311-ddtrace-webbpsf/lib/python3.11/site-packages/webbpsf/gridded_library.py:436: in to_model
    ndd.meta['grid_xypos'] = [((float(ndd.meta[key][0].split(',')[1].split(')')[0])),
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

.0 = <odict_iterator object at 0x7f6c6ed3f100>

>   ndd.meta['grid_xypos'] = [((float(ndd.meta[key][0].split(',')[1].split(')')[0])),
                              (float(ndd.meta[key][0].split(',')[0].split('(')[1])))
                              for key in ndd.meta.keys() if "DET_YX" in key]
E   ValueError: could not convert string to float: ' np.float64(100.0'
```

**Comment by BradleySappington** [comment]
@braingram - I reopened, however I have been unable to reproduce the issue locally in webbpsf.  (we are now on version 1.3.0, not 1.2.1 which romancal is currently set to use).  

I also ran a few tests in romancal on my machine and the error did not occur.  Can you please provide the complete ValueError from the output, and any steps on how to reproduce?

**Comment by braingram** [comment]
Thanks. I didn't know romancal used an exact pin for webbpsf. I ran the previously failing unit test with 1.3.0 and it passed for me as well.

I opened a PR for romancal to remove the exact pin but I think given your investigation that this is a romancal and not a webbpsf issue. I'll close this issue and thanks for the detective work!

**Comment by BradleySappington** [comment]
@braingram awesome, good luck!
