### ISSUE TITLE
Read/load saved PSF grid?

### ISSUE THREAD

**Issue by keflavich** [spacetelescope/webbpsf#769]
The gridded library has a `save=` option that saves the resulting data to a FITS file.  I can't find a 'read' function.  I think it's basically the `to_model` function, but some modifications are needed to handle differences between the FITS header and the dict.

```python
gridfh = fits.open('saved_webbpsf_grid_filename.fits')
ndd = NDData(gridfh[0].data, meta=dict(gridfh[0].header))
ndd.meta['grid_xypos'] = [((float(ndd.meta[key].split(',')[1].split(')')[0])),
                                  (float(ndd.meta[key].split(',')[0].split('(')[1])))
                                  for key in ndd.meta.keys() if "DET_YX" in key]

ndd.meta['oversampling'] = ndd.meta["OVERSAMP"]  # just pull the value
ndd.meta = {key.lower(): ndd.meta[key] for key in ndd.meta}

model = GriddedPSFModel(ndd)
```

If this is right, it should be added somewhere - I'm not sure where though.

**Comment by mperrin** [comment]
This sounds like a question for @larrybradley. I believe their next version of photutils will natively be able to read these files, I think?

**Comment by keflavich** [comment]
So... apparently I have write-only memory.  I have proof that I knew about this code in the past:
https://github.com/spacetelescope/webbpsf/blob/b45e76f9e2dcc0b37f6e569fa3af07033d0b4144/webbpsf/utils.py#L814
and it is indeed exactly what I proposed above.  The reader exists, I just failed to find it yesterday.  I searched for the terms 'read' and 'load', which are absent from the docstring.

It might be a good idea to link to this reader in the documentation a bit more, maybe in the writer?

**Comment by larrybradley** [comment]
@keflavich With the next version of `photutils` (to be released by Wed) you can use:
 `psfmodel = GriddedPSFModel.read('<webbpdf_file>.fits')`

**Comment by keflavich** [comment]
@larrybradley could you link to the relevant PR?  Is the save machinery also in photutils now?

**Comment by larrybradley** [comment]
@keflavich Yes, it's in `main`.  PR: https://github.com/astropy/photutils/pull/1654
