### ISSUE TITLE
MIRI cruciform detector effects not in Read the Docs

### ISSUE THREAD

**Issue by liztino** [spacetelescope/webbpsf#780]
I was investigating whether the newest version of WebbPSF (v1.2.1) contains an estimate of the MIRI cruciform effect. It appears the code does account for the cruciform (through [this pull request](https://github.com/spacetelescope/webbpsf/pull/693) and in Libralato et al. 2023) but I could not find whether the cruciform detector effect is included in the Read the Docs page. Would you be able to add it? 

Thank you!

**Comment by marcio-melendez** [comment]
@liztino yes, we can add some information into the Read the Docs page. We also have a current issue to improve the MIRI cruciform, spacetelescope/stpsf#35 . In the meantime, you can read more about the cruciform implementation under `detectors`. 
Thanks!

**Comment by liztino** [comment]
Great, thank you!
