### ISSUE TITLE
AttributeError: 'MIRI' object has no attribute 'load_wss_opd_by_date'

### ISSUE THREAD

**Issue by MTLeist255** [spacetelescope/webbpsf#788]
Hello, I am trying to generate MIRI PSFs with optical paths closest to the dates of my observations and am receiving the following error message:

AttributeError: 'MIRI' object has no attribute 'load_wss_opd_by_date'

It was my understanding from the user-docs (https://webbpsf.readthedocs.io/en/latest/jwst_measured_opds.html) to call 'load_wss_opd_by_date" I could just run:

miri = webbpsf.MIRI()
miri.filter = 'F560W'
miri.load_wss_opd_by_date('2023-07-07T13:33:30.016', plot=True)

Are you able to generate MIRI PSFs using the optical path closest to your observation in WebbPSF?

**Comment by marcio-melendez** [comment]
Hi, 
It is likely something with your installation. Make sure to have the latest stable or dev version of webbpsf. I just ran the code you provided above  and got the following results:
`iterating query, tdelta=3.0

MAST OPD query around UTC: 2023-07-07T13:33:30.016
                        MJD: 60132.564930740744

OPD immediately preceding the given datetime:
	URI:	 mast:JWST/product/R2023070603-NRCA3_FP1-1.fits
	Date (MJD):	 60130.8058
	Delta time:	 -1.7591 days

OPD immediately following the given datetime:
	URI:	 mast:JWST/product/R2023070803-NRCA3_FP1-1.fits
	Date (MJD):	 60132.6431
	Delta time:	 0.0781 days
User requested choosing OPD time closest in time to 2023-07-07T13:33:30.016, which is R2023070803-NRCA3_FP1-1.fits, delta time 0.078 days
Downloading URL https://mast.stsci.edu/api/v0.1/Download/file?uri=mast:JWST/product/R2023070803-NRCA3_FP1-1.fits to /Users/melendez/WFSC_Flight/webbpsf-data_1_2_1/webbpsf-data/MAST_JWST_WSS_OPDs/R2023070803-NRCA3_FP1-1.fits ... [Done]
Importing and format-converting OPD from /Users/melendez/WFSC_Flight/webbpsf-data_1_2_1/webbpsf-data/MAST_JWST_WSS_OPDs/R2023070803-NRCA3_FP1-1.fits
Backing out SI WFE and OTE field dependence at the WF sensing field point`
![image](https://github.com/spacetelescope/webbpsf/assets/9635910/2ebc77ae-1506-41f7-90c4-3af1599d4b8c)

**Comment by mperrin** [comment]
Hi @MTLeist255, I wanted to follow up on this issue. Were you able to resolve it by updating to a more recent version of webbpsf? Please let us know if you're still having any issues or not. Thanks.

**Comment by MTLeist255** [comment]
Hi @mperrin and @obi-wan76 my sincere apologies for my delayed reply, yes this resolved the issue I was having thank you very much!

**Comment by mperrin** [comment]
Great! No need to apologize. :-) We're just glad to know that it's all working for you now. Cheers.
