### ISSUE TITLE
PSF model worse for brightsky detector

### ISSUE THREAD

**Issue by amn3142** [spacetelescope/webbpsf#805]
Hi I was wondering if there is any expectation that the PSF model would be systematically worse/different for detector sub-arrays? We are finding relatively worse xisq fits when applying webbpsf to data taken with e.g. BRIGHTSKY readout mode.

**Comment by mperrin** [comment]
Hi @amn3142, this is the first I've heard of anything like this. It's not obvious what could cause a difference depending on detector readout mode. I think there is not an expectation that the PSF would be systematically different for subarray modes. 

Can you provide an example of particular datasets or filenames that you're seeing this in, please? We can take a look.

**Comment by mperrin** [comment]
@amn3142 hi again, wanted to follow up on this issue you had reported. Can you give us please some example file names for data you’re seeing this with? That would let us take a look here and see what we can figure out.

**Comment by amn3142** [comment]
@mperrin I think the issue is actually related to how the uncertainties are being calculated rather than with the psf model itself. Sorry, I'll close this. On another note, do you know if there is any progress with including the detector effects in the supersampled psf output?
