### ISSUE TITLE
A typo in NIRSpec.disperser_list

### ISSUE THREAD

**Issue by WenkeRen** [spacetelescope/webbpsf#888]
Hi there,

I find that the G395M is not accepted when it is set to `disperser` of class `NIRSpec`. It is possibly due to a typo at the line 3171 of [webbpsf_core.py](https://github.com/spacetelescope/webbpsf/blob/develop/webbpsf/webbpsf_core.py), which wrongly spells the name as G394M. I'm not sure if this typo would caused any further error. Please check, thanks.

**Comment by mperrin** [comment]
Thank you @WenkeRen. You're completely correct, that typo is the problem. Thanks much for bringing that to our attention. We'll fix that ASAP in the code here on GitHub, and you can also simply edit that line of the code in your local copy  to get it working for you right away there. Cheers and thanks again.
