### ISSUE TITLE
webbpsf stopped working for NIRCam F150W2

### ISSUE THREAD

**Issue by WeichenStars** [spacetelescope/webbpsf#921]
Hi everyone,

I've been using the most recent version of webbpsf (v1.4.0) for some imaging data taken with the NIRCam ultra-wide filters, F150W2 and F322W2, and encountered this issue. 

Everything went as normal with the F322W2. 

But with the NIRCam/F150W2, the following error message would show up with no output psf returned:

```
nc = webbpsf.NIRCam()

nc.filter='F150W2'

psf150W2 = nc.calc_psf()
```

> Cell In[21], line 3
>       1 nc = webbpsf.NIRCam()
>       2 nc.filter='F150W2'
> ----> 3 psf150W2 = nc.calc_psf()
> 
> File ~/anaconda3/envs/webbpsf-new/lib/python3.12/site-packages/webbpsf/webbpsf_core.py:1213, in JWInstrument.calc_psf(self, outfile, source, nlambda, monochromatic, fov_arcsec, fov_pixels, oversample, detector_oversample, fft_oversample, overwrite, display, save_intermediates, return_intermediates, normalize, add_distortion, crop_psf)
>    1210         self.pupil.update_opd()
>    1212 # Run poppy calc_psf
> -> 1213 psf = SpaceTelescopeInstrument.calc_psf(
>    1214     self,
>    1215     outfile=outfile,
>    1216     source=source,
>    1217     nlambda=nlambda,
>    1218     monochromatic=monochromatic,
>    1219     fov_arcsec=fov_arcsec,
>    1220     fov_pixels=fov_pixels,
>    1221     oversample=oversample,
>    1222     detector_oversample=detector_oversample,
>    1223     fft_oversample=fft_oversample,
>    1224     overwrite=overwrite,
>    1225     display=display,
>    1226     save_intermediates=save_intermediates,
>    1227     return_intermediates=return_intermediates,
>    1228     normalize=normalize,
>    1229 )
>    1231 return psf
> 
> File ~/anaconda3/envs/webbpsf-new/lib/python3.12/site-packages/poppy/instrument.py:251, in Instrument.calc_psf(self, outfile, source, nlambda, monochromatic, fov_arcsec, fov_pixels, oversample, detector_oversample, fft_oversample, overwrite, display, save_intermediates, return_intermediates, normalize)
>     247 wavelens, weights = self._get_weights(source=source, nlambda=local_options['nlambda'],
>     248                                       monochromatic=local_options['monochromatic'])
>     250 # Validate that the calculation we're about to do makes sense with this instrument config
> --> 251 self._validate_config(wavelengths=wavelens)
>     252 poppy_core._log.info(
>     253     "PSF calc using fov_%s, oversample = %d, number of wavelengths = %d" % (
>     254         local_options['fov_spec'], local_options['detector_oversample'], len(wavelens)
>     255     )
>     256 )
>     258 # ---- now at last, actually do the PSF calc:
>     259 #  instantiate an optical system using the current parameters
> 
> File ~/anaconda3/envs/webbpsf-new/lib/python3.12/site-packages/webbpsf/webbpsf_core.py:2884, in NIRCam._validate_config(self, **kwargs)
>    2882     raise RuntimeError('The requested wavelengths are too long to be imaged with NIRCam')
>    2883 if self.channel == 'short' and np.max(wavelengths) > self.SHORT_WAVELENGTH_MAX:
> -> 2884     raise RuntimeError('The requested wavelengths are too long for NIRCam short wave channel.')
>    2885 if self.channel == 'long' and np.min(wavelengths) < self.LONG_WAVELENGTH_MIN:
>    2886     raise RuntimeError('The requested wavelengths are too short for NIRCam long wave channel.')
> 
> RuntimeError: The requested wavelengths are too long for NIRCam short wave channel.

I'd really appreciate it if someone could look into this!

Thanks,
Weichen

**Comment by WeichenStars** [comment]
Just following up, if I specify the wavelength or nlambda parameter in the calc_psf function, everything would run as normal with F150W2, namely something like:

`psf150w2 = nc.calc_psf(monochromatic = 2.0e-6)`

or

`psf150W2 = nc.calc_psf(nlambda = 5)`

**Comment by marcio-melendez** [comment]
Hi @WeichenStars , 
Yes, this is a known issue because of some partial overlapping between filters and a simple approximation when defining the filter range cutoff. 
A simple workaround is to change the maximum wavelength range for the SW filter. 

```
nc = webbpsf.NIRCam()

nc.SHORT_WAVELENGTH_MAX = 2.5e-06 # or any value above the current max of the filter 2.36261443e-06

nc.filter='F150W2'

psf150W2 = nc.calc_psf()
```
Thanks!

**Comment by WeichenStars** [comment]
That worked, thanks!!
